# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.credential_key import CredentialKey

class TestCredentialKey(unittest.TestCase):
    """CredentialKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialKey:
        """Test CredentialKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialKey`
        """
        model = CredentialKey()
        if include_optional:
            return CredentialKey(
                type = 'key',
                key = '',
                metadata = opencode_sdk.models.metadata.metadata()
            )
        else:
            return CredentialKey(
                type = 'key',
                key = '',
        )
        """

    def testCredentialKey(self):
        """Test CredentialKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
