# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_session_next_revert_cleared import EventSessionNextRevertCleared

class TestEventSessionNextRevertCleared(unittest.TestCase):
    """EventSessionNextRevertCleared unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventSessionNextRevertCleared:
        """Test EventSessionNextRevertCleared
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventSessionNextRevertCleared`
        """
        model = EventSessionNextRevertCleared()
        if include_optional:
            return EventSessionNextRevertCleared(
                id = 'evt_',
                type = 'session.next.revert.cleared',
                properties = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', )
            )
        else:
            return EventSessionNextRevertCleared(
                id = 'evt_',
                type = 'session.next.revert.cleared',
                properties = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', ),
        )
        """

    def testEventSessionNextRevertCleared(self):
        """Test EventSessionNextRevertCleared"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
