# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_message_tool_state_error import SessionMessageToolStateError

class TestSessionMessageToolStateError(unittest.TestCase):
    """SessionMessageToolStateError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionMessageToolStateError:
        """Test SessionMessageToolStateError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionMessageToolStateError`
        """
        model = SessionMessageToolStateError()
        if include_optional:
            return SessionMessageToolStateError(
                status = 'error',
                input = None,
                content = [
                    null
                    ],
                structured = None,
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', ),
                result = None
            )
        else:
            return SessionMessageToolStateError(
                status = 'error',
                input = None,
                content = [
                    null
                    ],
                structured = None,
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', ),
        )
        """

    def testSessionMessageToolStateError(self):
        """Test SessionMessageToolStateError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
