# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of24 import GlobalEventPayloadAnyOf24

class TestGlobalEventPayloadAnyOf24(unittest.TestCase):
    """GlobalEventPayloadAnyOf24 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf24:
        """Test GlobalEventPayloadAnyOf24
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf24`
        """
        model = GlobalEventPayloadAnyOf24()
        if include_optional:
            return GlobalEventPayloadAnyOf24(
                id = 'evt_',
                type = 'session.next.text.delta',
                properties = opencode_sdk.models.global_event_payload_any_of_24_properties.GlobalEvent_payload_anyOf_24_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    text_id = '', 
                    delta = '', )
            )
        else:
            return GlobalEventPayloadAnyOf24(
                id = 'evt_',
                type = 'session.next.text.delta',
                properties = opencode_sdk.models.global_event_payload_any_of_24_properties.GlobalEvent_payload_anyOf_24_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    text_id = '', 
                    delta = '', ),
        )
        """

    def testGlobalEventPayloadAnyOf24(self):
        """Test GlobalEventPayloadAnyOf24"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
