# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.experimental_workspace_create_request import ExperimentalWorkspaceCreateRequest

class TestExperimentalWorkspaceCreateRequest(unittest.TestCase):
    """ExperimentalWorkspaceCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExperimentalWorkspaceCreateRequest:
        """Test ExperimentalWorkspaceCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExperimentalWorkspaceCreateRequest`
        """
        model = ExperimentalWorkspaceCreateRequest()
        if include_optional:
            return ExperimentalWorkspaceCreateRequest(
                id = 'wrk',
                type = '',
                branch = '',
                extra = None
            )
        else:
            return ExperimentalWorkspaceCreateRequest(
                type = '',
        )
        """

    def testExperimentalWorkspaceCreateRequest(self):
        """Test ExperimentalWorkspaceCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
