# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of50 import GlobalEventPayloadAnyOf50

class TestGlobalEventPayloadAnyOf50(unittest.TestCase):
    """GlobalEventPayloadAnyOf50 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf50:
        """Test GlobalEventPayloadAnyOf50
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf50`
        """
        model = GlobalEventPayloadAnyOf50()
        if include_optional:
            return GlobalEventPayloadAnyOf50(
                id = 'evt_',
                type = 'permission.v2.asked',
                properties = opencode_sdk.models.global_event_payload_any_of_50_properties.GlobalEvent_payload_anyOf_50_properties(
                    id = 'per', 
                    session_id = 'ses', 
                    action = '', 
                    resources = [
                        ''
                        ], 
                    save = [
                        ''
                        ], 
                    metadata = opencode_sdk.models.metadata.metadata(), 
                    source = opencode_sdk.models.permission_v2_source.PermissionV2Source(
                        type = 'tool', 
                        message_id = '', 
                        call_id = '', ), )
            )
        else:
            return GlobalEventPayloadAnyOf50(
                id = 'evt_',
                type = 'permission.v2.asked',
                properties = opencode_sdk.models.global_event_payload_any_of_50_properties.GlobalEvent_payload_anyOf_50_properties(
                    id = 'per', 
                    session_id = 'ses', 
                    action = '', 
                    resources = [
                        ''
                        ], 
                    save = [
                        ''
                        ], 
                    metadata = opencode_sdk.models.metadata.metadata(), 
                    source = opencode_sdk.models.permission_v2_source.PermissionV2Source(
                        type = 'tool', 
                        message_id = '', 
                        call_id = '', ), ),
        )
        """

    def testGlobalEventPayloadAnyOf50(self):
        """Test GlobalEventPayloadAnyOf50"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
