# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.api.workspace_api import WorkspaceApi


class TestWorkspaceApi(unittest.IsolatedAsyncioTestCase):
    """WorkspaceApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WorkspaceApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_experimental_workspace_adapter_list(self) -> None:
        """Test case for experimental_workspace_adapter_list

        List workspace adapters
        """
        pass

    def test_experimental_workspace_adapter_list_sync(self) -> None:
        """Test case for experimental_workspace_adapter_list (synchronous)

        List workspace adapters
        """
        pass

    async def test_experimental_workspace_create(self) -> None:
        """Test case for experimental_workspace_create

        Create workspace
        """
        pass

    def test_experimental_workspace_create_sync(self) -> None:
        """Test case for experimental_workspace_create (synchronous)

        Create workspace
        """
        pass

    async def test_experimental_workspace_list(self) -> None:
        """Test case for experimental_workspace_list

        List workspaces
        """
        pass

    def test_experimental_workspace_list_sync(self) -> None:
        """Test case for experimental_workspace_list (synchronous)

        List workspaces
        """
        pass

    async def test_experimental_workspace_remove(self) -> None:
        """Test case for experimental_workspace_remove

        Remove workspace
        """
        pass

    def test_experimental_workspace_remove_sync(self) -> None:
        """Test case for experimental_workspace_remove (synchronous)

        Remove workspace
        """
        pass

    async def test_experimental_workspace_status(self) -> None:
        """Test case for experimental_workspace_status

        Workspace status
        """
        pass

    def test_experimental_workspace_status_sync(self) -> None:
        """Test case for experimental_workspace_status (synchronous)

        Workspace status
        """
        pass

    async def test_experimental_workspace_sync_list(self) -> None:
        """Test case for experimental_workspace_sync_list

        Sync workspace list
        """
        pass

    def test_experimental_workspace_sync_list_sync(self) -> None:
        """Test case for experimental_workspace_sync_list (synchronous)

        Sync workspace list
        """
        pass

    async def test_experimental_workspace_warp(self) -> None:
        """Test case for experimental_workspace_warp

        Warp session into workspace
        """
        pass

    def test_experimental_workspace_warp_sync(self) -> None:
        """Test case for experimental_workspace_warp (synchronous)

        Warp session into workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
