# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_event_session_created_sync_event import SyncEventSessionCreatedSyncEvent

class TestSyncEventSessionCreatedSyncEvent(unittest.TestCase):
    """SyncEventSessionCreatedSyncEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncEventSessionCreatedSyncEvent:
        """Test SyncEventSessionCreatedSyncEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncEventSessionCreatedSyncEvent`
        """
        model = SyncEventSessionCreatedSyncEvent()
        if include_optional:
            return SyncEventSessionCreatedSyncEvent(
                type = 'session.created.1',
                id = 'evt_',
                seq = 1.337,
                aggregate_id = '',
                data = opencode_sdk.models.global_event_payload_any_of_4_properties.GlobalEvent_payload_anyOf_4_properties(
                    session_id = 'ses', 
                    info = opencode_sdk.models.session.Session(
                        id = 'ses', 
                        slug = '', 
                        project_id = '', 
                        workspace_id = 'wrk', 
                        directory = '', 
                        path = '', 
                        parent_id = 'ses', 
                        summary = opencode_sdk.models.session_summary.Session_summary(
                            additions = 1.337, 
                            deletions = 1.337, 
                            files = 1.337, 
                            diffs = [
                                opencode_sdk.models.snapshot_file_diff.SnapshotFileDiff(
                                    file = '', 
                                    patch = '', 
                                    additions = 1.337, 
                                    deletions = 1.337, 
                                    status = 'added', )
                                ], ), 
                        cost = 1.337, 
                        tokens = opencode_sdk.models.session_tokens.Session_tokens(
                            input = 1.337, 
                            output = 1.337, 
                            reasoning = 1.337, 
                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                read = 1.337, 
                                write = 1.337, ), ), 
                        share = opencode_sdk.models.session_share.Session_share(
                            url = '', ), 
                        title = '', 
                        agent = '', 
                        model = opencode_sdk.models.session_create_request_model.session_create_request_model(
                            id = '', 
                            provider_id = '', 
                            variant = '', ), 
                        version = '', 
                        metadata = opencode_sdk.models.metadata.metadata(), 
                        time = opencode_sdk.models.session_time.Session_time(
                            created = 0, 
                            updated = 0, 
                            compacting = 0, 
                            archived = 1.337, ), 
                        permission = [
                            opencode_sdk.models.permission_rule.PermissionRule(
                                permission = '', 
                                pattern = '', 
                                action = 'allow', )
                            ], 
                        revert = opencode_sdk.models.session_revert.Session_revert(
                            message_id = 'msg', 
                            part_id = 'prt', 
                            snapshot = '', 
                            diff = '', ), ), )
            )
        else:
            return SyncEventSessionCreatedSyncEvent(
                type = 'session.created.1',
                id = 'evt_',
                seq = 1.337,
                aggregate_id = '',
                data = opencode_sdk.models.global_event_payload_any_of_4_properties.GlobalEvent_payload_anyOf_4_properties(
                    session_id = 'ses', 
                    info = opencode_sdk.models.session.Session(
                        id = 'ses', 
                        slug = '', 
                        project_id = '', 
                        workspace_id = 'wrk', 
                        directory = '', 
                        path = '', 
                        parent_id = 'ses', 
                        summary = opencode_sdk.models.session_summary.Session_summary(
                            additions = 1.337, 
                            deletions = 1.337, 
                            files = 1.337, 
                            diffs = [
                                opencode_sdk.models.snapshot_file_diff.SnapshotFileDiff(
                                    file = '', 
                                    patch = '', 
                                    additions = 1.337, 
                                    deletions = 1.337, 
                                    status = 'added', )
                                ], ), 
                        cost = 1.337, 
                        tokens = opencode_sdk.models.session_tokens.Session_tokens(
                            input = 1.337, 
                            output = 1.337, 
                            reasoning = 1.337, 
                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                read = 1.337, 
                                write = 1.337, ), ), 
                        share = opencode_sdk.models.session_share.Session_share(
                            url = '', ), 
                        title = '', 
                        agent = '', 
                        model = opencode_sdk.models.session_create_request_model.session_create_request_model(
                            id = '', 
                            provider_id = '', 
                            variant = '', ), 
                        version = '', 
                        metadata = opencode_sdk.models.metadata.metadata(), 
                        time = opencode_sdk.models.session_time.Session_time(
                            created = 0, 
                            updated = 0, 
                            compacting = 0, 
                            archived = 1.337, ), 
                        permission = [
                            opencode_sdk.models.permission_rule.PermissionRule(
                                permission = '', 
                                pattern = '', 
                                action = 'allow', )
                            ], 
                        revert = opencode_sdk.models.session_revert.Session_revert(
                            message_id = 'msg', 
                            part_id = 'prt', 
                            snapshot = '', 
                            diff = '', ), ), ),
        )
        """

    def testSyncEventSessionCreatedSyncEvent(self):
        """Test SyncEventSessionCreatedSyncEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
