# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.config_compaction import ConfigCompaction

class TestConfigCompaction(unittest.TestCase):
    """ConfigCompaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigCompaction:
        """Test ConfigCompaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigCompaction`
        """
        model = ConfigCompaction()
        if include_optional:
            return ConfigCompaction(
                auto = True,
                prune = True,
                tail_turns = 0,
                preserve_recent_tokens = 0,
                reserved = 0
            )
        else:
            return ConfigCompaction(
        )
        """

    def testConfigCompaction(self):
        """Test ConfigCompaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
