# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.vcs_branch_updated import VcsBranchUpdated

class TestVcsBranchUpdated(unittest.TestCase):
    """VcsBranchUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VcsBranchUpdated:
        """Test VcsBranchUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VcsBranchUpdated`
        """
        model = VcsBranchUpdated()
        if include_optional:
            return VcsBranchUpdated(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'vcs.branch.updated',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.global_event_payload_any_of_80_properties.GlobalEvent_payload_anyOf_80_properties(
                    branch = '', )
            )
        else:
            return VcsBranchUpdated(
                id = 'evt_',
                type = 'vcs.branch.updated',
                data = opencode_sdk.models.global_event_payload_any_of_80_properties.GlobalEvent_payload_anyOf_80_properties(
                    branch = '', ),
        )
        """

    def testVcsBranchUpdated(self):
        """Test VcsBranchUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
