# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.project_copy_error import ProjectCopyError

class TestProjectCopyError(unittest.TestCase):
    """ProjectCopyError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCopyError:
        """Test ProjectCopyError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCopyError`
        """
        model = ProjectCopyError()
        if include_optional:
            return ProjectCopyError(
                name = 'ProjectCopyError',
                data = opencode_sdk.models.project_copy_error_data.ProjectCopyError_data(
                    message = '', 
                    force_required = True, )
            )
        else:
            return ProjectCopyError(
                name = 'ProjectCopyError',
                data = opencode_sdk.models.project_copy_error_data.ProjectCopyError_data(
                    message = '', 
                    force_required = True, ),
        )
        """

    def testProjectCopyError(self):
        """Test ProjectCopyError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
