# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_auth_method_prompts_inner_any_of import ProviderAuthMethodPromptsInnerAnyOf

class TestProviderAuthMethodPromptsInnerAnyOf(unittest.TestCase):
    """ProviderAuthMethodPromptsInnerAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderAuthMethodPromptsInnerAnyOf:
        """Test ProviderAuthMethodPromptsInnerAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderAuthMethodPromptsInnerAnyOf`
        """
        model = ProviderAuthMethodPromptsInnerAnyOf()
        if include_optional:
            return ProviderAuthMethodPromptsInnerAnyOf(
                type = 'text',
                key = '',
                message = '',
                placeholder = '',
                when = opencode_sdk.models.provider_auth_method_prompts_inner_any_of_when.ProviderAuthMethod_prompts_inner_anyOf_when(
                    key = '', 
                    op = 'eq', 
                    value = '', )
            )
        else:
            return ProviderAuthMethodPromptsInnerAnyOf(
                type = 'text',
                key = '',
                message = '',
        )
        """

    def testProviderAuthMethodPromptsInnerAnyOf(self):
        """Test ProviderAuthMethodPromptsInnerAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
