# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.location_ref import LocationRef

class TestLocationRef(unittest.TestCase):
    """LocationRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationRef:
        """Test LocationRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationRef`
        """
        model = LocationRef()
        if include_optional:
            return LocationRef(
                directory = '',
                workspace_id = 'wrk'
            )
        else:
            return LocationRef(
                directory = '',
        )
        """

    def testLocationRef(self):
        """Test LocationRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
