# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_auth_error_data import ProviderAuthErrorData

class TestProviderAuthErrorData(unittest.TestCase):
    """ProviderAuthErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderAuthErrorData:
        """Test ProviderAuthErrorData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderAuthErrorData`
        """
        model = ProviderAuthErrorData()
        if include_optional:
            return ProviderAuthErrorData(
                provider_id = '',
                message = ''
            )
        else:
            return ProviderAuthErrorData(
                provider_id = '',
                message = '',
        )
        """

    def testProviderAuthErrorData(self):
        """Test ProviderAuthErrorData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
