# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_next_retry_error import SessionNextRetryError

class TestSessionNextRetryError(unittest.TestCase):
    """SessionNextRetryError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionNextRetryError:
        """Test SessionNextRetryError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionNextRetryError`
        """
        model = SessionNextRetryError()
        if include_optional:
            return SessionNextRetryError(
                message = '',
                status_code = 1.337,
                is_retryable = True,
                response_headers = {
                    'key' : ''
                    },
                response_body = '',
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return SessionNextRetryError(
                message = '',
                is_retryable = True,
        )
        """

    def testSessionNextRetryError(self):
        """Test SessionNextRetryError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
