# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.v2_session_prompt200_response import V2SessionPrompt200Response

class TestV2SessionPrompt200Response(unittest.TestCase):
    """V2SessionPrompt200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2SessionPrompt200Response:
        """Test V2SessionPrompt200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2SessionPrompt200Response`
        """
        model = V2SessionPrompt200Response()
        if include_optional:
            return V2SessionPrompt200Response(
                data = opencode_sdk.models.session_input_admitted.SessionInputAdmitted(
                    admitted_seq = 0, 
                    id = 'msg_', 
                    session_id = 'ses', 
                    prompt = opencode_sdk.models.prompt.Prompt(
                        text = '', 
                        files = [
                            opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                                uri = '', 
                                mime = '', 
                                name = '', 
                                description = '', 
                                source = opencode_sdk.models.prompt_source.PromptSource(
                                    start = 1.337, 
                                    end = 1.337, 
                                    text = '', ), )
                            ], 
                        agents = [
                            opencode_sdk.models.prompt_agent_attachment.PromptAgentAttachment(
                                name = '', )
                            ], ), 
                    delivery = 'steer', 
                    time_created = 1.337, 
                    promoted_seq = 0, )
            )
        else:
            return V2SessionPrompt200Response(
                data = opencode_sdk.models.session_input_admitted.SessionInputAdmitted(
                    admitted_seq = 0, 
                    id = 'msg_', 
                    session_id = 'ses', 
                    prompt = opencode_sdk.models.prompt.Prompt(
                        text = '', 
                        files = [
                            opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                                uri = '', 
                                mime = '', 
                                name = '', 
                                description = '', 
                                source = opencode_sdk.models.prompt_source.PromptSource(
                                    start = 1.337, 
                                    end = 1.337, 
                                    text = '', ), )
                            ], 
                        agents = [
                            opencode_sdk.models.prompt_agent_attachment.PromptAgentAttachment(
                                name = '', )
                            ], ), 
                    delivery = 'steer', 
                    time_created = 1.337, 
                    promoted_seq = 0, ),
        )
        """

    def testV2SessionPrompt200Response(self):
        """Test V2SessionPrompt200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
