# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.config_references_value import ConfigReferencesValue

class TestConfigReferencesValue(unittest.TestCase):
    """ConfigReferencesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigReferencesValue:
        """Test ConfigReferencesValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigReferencesValue`
        """
        model = ConfigReferencesValue()
        if include_optional:
            return ConfigReferencesValue(
                repository = '',
                branch = '',
                description = '',
                hidden = True,
                path = ''
            )
        else:
            return ConfigReferencesValue(
                repository = '',
                path = '',
        )
        """

    def testConfigReferencesValue(self):
        """Test ConfigReferencesValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
