# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_server_instance_disposed import EventServerInstanceDisposed

class TestEventServerInstanceDisposed(unittest.TestCase):
    """EventServerInstanceDisposed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventServerInstanceDisposed:
        """Test EventServerInstanceDisposed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventServerInstanceDisposed`
        """
        model = EventServerInstanceDisposed()
        if include_optional:
            return EventServerInstanceDisposed(
                id = '',
                type = 'server.instance.disposed',
                properties = opencode_sdk.models.event_server_instance_disposed_properties.EventServerInstanceDisposed_properties(
                    directory = '', )
            )
        else:
            return EventServerInstanceDisposed(
                id = '',
                type = 'server.instance.disposed',
                properties = opencode_sdk.models.event_server_instance_disposed_properties.EventServerInstanceDisposed_properties(
                    directory = '', ),
        )
        """

    def testEventServerInstanceDisposed(self):
        """Test EventServerInstanceDisposed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
