# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_event_session_next_step_ended import SyncEventSessionNextStepEnded

class TestSyncEventSessionNextStepEnded(unittest.TestCase):
    """SyncEventSessionNextStepEnded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncEventSessionNextStepEnded:
        """Test SyncEventSessionNextStepEnded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncEventSessionNextStepEnded`
        """
        model = SyncEventSessionNextStepEnded()
        if include_optional:
            return SyncEventSessionNextStepEnded(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_session_next_step_ended_sync_event.SyncEventSessionNextStepEnded_syncEvent(
                    type = 'session.next.step.ended.2', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_21_properties.GlobalEvent_payload_anyOf_21_properties(
                        timestamp = 1.337, 
                        session_id = 'ses', 
                        assistant_message_id = 'msg_', 
                        finish = '', 
                        cost = 1.337, 
                        tokens = opencode_sdk.models.session_tokens.Session_tokens(
                            input = 1.337, 
                            output = 1.337, 
                            reasoning = 1.337, 
                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                read = 1.337, 
                                write = 1.337, ), ), 
                        snapshot = '', 
                        files = [
                            ''
                            ], ), )
            )
        else:
            return SyncEventSessionNextStepEnded(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_session_next_step_ended_sync_event.SyncEventSessionNextStepEnded_syncEvent(
                    type = 'session.next.step.ended.2', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_21_properties.GlobalEvent_payload_anyOf_21_properties(
                        timestamp = 1.337, 
                        session_id = 'ses', 
                        assistant_message_id = 'msg_', 
                        finish = '', 
                        cost = 1.337, 
                        tokens = opencode_sdk.models.session_tokens.Session_tokens(
                            input = 1.337, 
                            output = 1.337, 
                            reasoning = 1.337, 
                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                read = 1.337, 
                                write = 1.337, ), ), 
                        snapshot = '', 
                        files = [
                            ''
                            ], ), ),
        )
        """

    def testSyncEventSessionNextStepEnded(self):
        """Test SyncEventSessionNextStepEnded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
