# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.config_v2_experimental_policy import ConfigV2ExperimentalPolicy

class TestConfigV2ExperimentalPolicy(unittest.TestCase):
    """ConfigV2ExperimentalPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigV2ExperimentalPolicy:
        """Test ConfigV2ExperimentalPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigV2ExperimentalPolicy`
        """
        model = ConfigV2ExperimentalPolicy()
        if include_optional:
            return ConfigV2ExperimentalPolicy(
                action = 'provider.use',
                effect = 'allow',
                resource = ''
            )
        else:
            return ConfigV2ExperimentalPolicy(
                action = 'provider.use',
                effect = 'allow',
                resource = '',
        )
        """

    def testConfigV2ExperimentalPolicy(self):
        """Test ConfigV2ExperimentalPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
