# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.tool_state_error import ToolStateError

class TestToolStateError(unittest.TestCase):
    """ToolStateError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolStateError:
        """Test ToolStateError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolStateError`
        """
        model = ToolStateError()
        if include_optional:
            return ToolStateError(
                status = 'error',
                input = opencode_sdk.models.metadata.metadata(),
                error = '',
                metadata = opencode_sdk.models.metadata.metadata(),
                time = opencode_sdk.models.tool_state_error_time.ToolStateError_time(
                    start = 0, 
                    end = 0, )
            )
        else:
            return ToolStateError(
                status = 'error',
                input = opencode_sdk.models.metadata.metadata(),
                error = '',
                time = opencode_sdk.models.tool_state_error_time.ToolStateError_time(
                    start = 0, 
                    end = 0, ),
        )
        """

    def testToolStateError(self):
        """Test ToolStateError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
