# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of32_properties_provider import GlobalEventPayloadAnyOf32PropertiesProvider

class TestGlobalEventPayloadAnyOf32PropertiesProvider(unittest.TestCase):
    """GlobalEventPayloadAnyOf32PropertiesProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf32PropertiesProvider:
        """Test GlobalEventPayloadAnyOf32PropertiesProvider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf32PropertiesProvider`
        """
        model = GlobalEventPayloadAnyOf32PropertiesProvider()
        if include_optional:
            return GlobalEventPayloadAnyOf32PropertiesProvider(
                executed = True,
                metadata = {
                    'key' : None
                    }
            )
        else:
            return GlobalEventPayloadAnyOf32PropertiesProvider(
                executed = True,
        )
        """

    def testGlobalEventPayloadAnyOf32PropertiesProvider(self):
        """Test GlobalEventPayloadAnyOf32PropertiesProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
