# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.unknown_error1 import UnknownError1

class TestUnknownError1(unittest.TestCase):
    """UnknownError1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnknownError1:
        """Test UnknownError1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnknownError1`
        """
        model = UnknownError1()
        if include_optional:
            return UnknownError1(
                tag = 'UnknownError',
                message = '',
                ref = ''
            )
        else:
            return UnknownError1(
                tag = 'UnknownError',
                message = '',
        )
        """

    def testUnknownError1(self):
        """Test UnknownError1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
