# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_project_updated import EventProjectUpdated

class TestEventProjectUpdated(unittest.TestCase):
    """EventProjectUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventProjectUpdated:
        """Test EventProjectUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventProjectUpdated`
        """
        model = EventProjectUpdated()
        if include_optional:
            return EventProjectUpdated(
                id = 'evt_',
                type = 'project.updated',
                properties = opencode_sdk.models.global_event_payload_any_of_73_properties.GlobalEvent_payload_anyOf_73_properties(
                    id = '', 
                    worktree = '', 
                    vcs = 'git', 
                    name = '', 
                    icon = opencode_sdk.models.project_icon.ProjectIcon(
                        url = '', 
                        override = '', 
                        color = '', ), 
                    commands = opencode_sdk.models.project_commands.ProjectCommands(
                        start = '', ), 
                    time = opencode_sdk.models.project_time.ProjectTime(
                        created = 0, 
                        updated = 0, 
                        initialized = 0, ), 
                    sandboxes = [
                        ''
                        ], )
            )
        else:
            return EventProjectUpdated(
                id = 'evt_',
                type = 'project.updated',
                properties = opencode_sdk.models.global_event_payload_any_of_73_properties.GlobalEvent_payload_anyOf_73_properties(
                    id = '', 
                    worktree = '', 
                    vcs = 'git', 
                    name = '', 
                    icon = opencode_sdk.models.project_icon.ProjectIcon(
                        url = '', 
                        override = '', 
                        color = '', ), 
                    commands = opencode_sdk.models.project_commands.ProjectCommands(
                        start = '', ), 
                    time = opencode_sdk.models.project_time.ProjectTime(
                        created = 0, 
                        updated = 0, 
                        initialized = 0, ), 
                    sandboxes = [
                        ''
                        ], ),
        )
        """

    def testEventProjectUpdated(self):
        """Test EventProjectUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
