# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.prompt import Prompt

class TestPrompt(unittest.TestCase):
    """Prompt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Prompt:
        """Test Prompt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Prompt`
        """
        model = Prompt()
        if include_optional:
            return Prompt(
                text = '',
                files = [
                    opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                        uri = '', 
                        mime = '', 
                        name = '', 
                        description = '', 
                        source = opencode_sdk.models.prompt_source.PromptSource(
                            start = 1.337, 
                            end = 1.337, 
                            text = '', ), )
                    ],
                agents = [
                    opencode_sdk.models.prompt_agent_attachment.PromptAgentAttachment(
                        name = '', 
                        source = opencode_sdk.models.prompt_source.PromptSource(
                            start = 1.337, 
                            end = 1.337, 
                            text = '', ), )
                    ]
            )
        else:
            return Prompt(
                text = '',
        )
        """

    def testPrompt(self):
        """Test Prompt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
