# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.tui_publish_request import TuiPublishRequest

class TestTuiPublishRequest(unittest.TestCase):
    """TuiPublishRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuiPublishRequest:
        """Test TuiPublishRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuiPublishRequest`
        """
        model = TuiPublishRequest()
        if include_optional:
            return TuiPublishRequest(
                type = 'tui.prompt.append',
                properties = opencode_sdk.models.tui_select_session_request.tui_selectSession_request(
                    session_id = 'ses', )
            )
        else:
            return TuiPublishRequest(
                type = 'tui.prompt.append',
                properties = opencode_sdk.models.tui_select_session_request.tui_selectSession_request(
                    session_id = 'ses', ),
        )
        """

    def testTuiPublishRequest(self):
        """Test TuiPublishRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
