# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_active import SessionActive

class TestSessionActive(unittest.TestCase):
    """SessionActive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionActive:
        """Test SessionActive
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionActive`
        """
        model = SessionActive()
        if include_optional:
            return SessionActive(
                type = 'running'
            )
        else:
            return SessionActive(
                type = 'running',
        )
        """

    def testSessionActive(self):
        """Test SessionActive"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
