# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.api.global_api import GlobalApi


class TestGlobalApi(unittest.IsolatedAsyncioTestCase):
    """GlobalApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = GlobalApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_global_config_get(self) -> None:
        """Test case for global_config_get

        Get global configuration
        """
        pass

    def test_global_config_get_sync(self) -> None:
        """Test case for global_config_get (synchronous)

        Get global configuration
        """
        pass

    async def test_global_config_update(self) -> None:
        """Test case for global_config_update

        Update global configuration
        """
        pass

    def test_global_config_update_sync(self) -> None:
        """Test case for global_config_update (synchronous)

        Update global configuration
        """
        pass

    async def test_global_dispose(self) -> None:
        """Test case for global_dispose

        Dispose instance
        """
        pass

    def test_global_dispose_sync(self) -> None:
        """Test case for global_dispose (synchronous)

        Dispose instance
        """
        pass

    async def test_global_event(self) -> None:
        """Test case for global_event

        Get global events
        """
        pass

    def test_global_event_sync(self) -> None:
        """Test case for global_event (synchronous)

        Get global events
        """
        pass

    async def test_global_health(self) -> None:
        """Test case for global_health

        Get health
        """
        pass

    def test_global_health_sync(self) -> None:
        """Test case for global_health (synchronous)

        Get health
        """
        pass

    async def test_global_upgrade(self) -> None:
        """Test case for global_upgrade

        Upgrade opencode
        """
        pass

    def test_global_upgrade_sync(self) -> None:
        """Test case for global_upgrade (synchronous)

        Upgrade opencode
        """
        pass


if __name__ == '__main__':
    unittest.main()
