# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.v2_session_question_list200_response import V2SessionQuestionList200Response

class TestV2SessionQuestionList200Response(unittest.TestCase):
    """V2SessionQuestionList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2SessionQuestionList200Response:
        """Test V2SessionQuestionList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2SessionQuestionList200Response`
        """
        model = V2SessionQuestionList200Response()
        if include_optional:
            return V2SessionQuestionList200Response(
                data = [
                    opencode_sdk.models.question_v2_request.QuestionV2Request(
                        id = 'que', 
                        session_id = 'ses', 
                        questions = [
                            opencode_sdk.models.question_v2_info.QuestionV2Info(
                                question = '', 
                                header = '', 
                                options = [
                                    opencode_sdk.models.question_v2_option.QuestionV2Option(
                                        label = '', 
                                        description = '', )
                                    ], 
                                multiple = True, 
                                custom = True, )
                            ], 
                        tool = opencode_sdk.models.question_v2_tool.QuestionV2Tool(
                            message_id = '', 
                            call_id = '', ), )
                    ]
            )
        else:
            return V2SessionQuestionList200Response(
                data = [
                    opencode_sdk.models.question_v2_request.QuestionV2Request(
                        id = 'que', 
                        session_id = 'ses', 
                        questions = [
                            opencode_sdk.models.question_v2_info.QuestionV2Info(
                                question = '', 
                                header = '', 
                                options = [
                                    opencode_sdk.models.question_v2_option.QuestionV2Option(
                                        label = '', 
                                        description = '', )
                                    ], 
                                multiple = True, 
                                custom = True, )
                            ], 
                        tool = opencode_sdk.models.question_v2_tool.QuestionV2Tool(
                            message_id = '', 
                            call_id = '', ), )
                    ],
        )
        """

    def testV2SessionQuestionList200Response(self):
        """Test V2SessionQuestionList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
