# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.skill_v2_embedded_source import SkillV2EmbeddedSource

class TestSkillV2EmbeddedSource(unittest.TestCase):
    """SkillV2EmbeddedSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillV2EmbeddedSource:
        """Test SkillV2EmbeddedSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillV2EmbeddedSource`
        """
        model = SkillV2EmbeddedSource()
        if include_optional:
            return SkillV2EmbeddedSource(
                type = 'embedded',
                skill = opencode_sdk.models.skill_v2_info.SkillV2Info(
                    name = '', 
                    description = '', 
                    slash = True, 
                    location = '', 
                    content = '', )
            )
        else:
            return SkillV2EmbeddedSource(
                type = 'embedded',
                skill = opencode_sdk.models.skill_v2_info.SkillV2Info(
                    name = '', 
                    description = '', 
                    slash = True, 
                    location = '', 
                    content = '', ),
        )
        """

    def testSkillV2EmbeddedSource(self):
        """Test SkillV2EmbeddedSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
