# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of61_properties import GlobalEventPayloadAnyOf61Properties

class TestGlobalEventPayloadAnyOf61Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf61Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf61Properties:
        """Test GlobalEventPayloadAnyOf61Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf61Properties`
        """
        model = GlobalEventPayloadAnyOf61Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf61Properties(
                session_id = 'ses',
                request_id = 'que'
            )
        else:
            return GlobalEventPayloadAnyOf61Properties(
                session_id = 'ses',
                request_id = 'que',
        )
        """

    def testGlobalEventPayloadAnyOf61Properties(self):
        """Test GlobalEventPayloadAnyOf61Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
