# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.message import Message

class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Message:
        """Test Message
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Message`
        """
        model = Message()
        if include_optional:
            return Message(
                id = 'msg',
                session_id = 'ses',
                role = 'assistant',
                time = opencode_sdk.models.assistant_message_time.AssistantMessage_time(
                    created = 0, 
                    completed = 0, ),
                format = None,
                summary = True,
                agent = '',
                model = opencode_sdk.models.user_message_model.UserMessage_model(
                    provider_id = '', 
                    model_id = '', 
                    variant = '', ),
                system = '',
                tools = {
                    'key' : True
                    },
                error = None,
                parent_id = 'msg',
                model_id = '',
                provider_id = '',
                mode = '',
                path = opencode_sdk.models.assistant_message_path.AssistantMessage_path(
                    cwd = '', 
                    root = '', ),
                cost = 1.337,
                tokens = opencode_sdk.models.assistant_message_tokens.AssistantMessage_tokens(
                    total = 1.337, 
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), ),
                structured = None,
                variant = '',
                finish = ''
            )
        else:
            return Message(
                id = 'msg',
                session_id = 'ses',
                role = 'assistant',
                time = opencode_sdk.models.assistant_message_time.AssistantMessage_time(
                    created = 0, 
                    completed = 0, ),
                agent = '',
                model = opencode_sdk.models.user_message_model.UserMessage_model(
                    provider_id = '', 
                    model_id = '', 
                    variant = '', ),
                parent_id = 'msg',
                model_id = '',
                provider_id = '',
                mode = '',
                path = opencode_sdk.models.assistant_message_path.AssistantMessage_path(
                    cwd = '', 
                    root = '', ),
                cost = 1.337,
                tokens = opencode_sdk.models.assistant_message_tokens.AssistantMessage_tokens(
                    total = 1.337, 
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), ),
        )
        """

    def testMessage(self):
        """Test Message"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
