# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of35_properties import GlobalEventPayloadAnyOf35Properties

class TestGlobalEventPayloadAnyOf35Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf35Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf35Properties:
        """Test GlobalEventPayloadAnyOf35Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf35Properties`
        """
        model = GlobalEventPayloadAnyOf35Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf35Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                call_id = '',
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', ),
                result = None,
                provider = opencode_sdk.models.global_event_payload_any_of_32_properties_provider.GlobalEvent_payload_anyOf_32_properties_provider(
                    executed = True, 
                    metadata = {
                        'key' : None
                        }, )
            )
        else:
            return GlobalEventPayloadAnyOf35Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                call_id = '',
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', ),
                provider = opencode_sdk.models.global_event_payload_any_of_32_properties_provider.GlobalEvent_payload_anyOf_32_properties_provider(
                    executed = True, 
                    metadata = {
                        'key' : None
                        }, ),
        )
        """

    def testGlobalEventPayloadAnyOf35Properties(self):
        """Test GlobalEventPayloadAnyOf35Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
