# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of52_properties import GlobalEventPayloadAnyOf52Properties

class TestGlobalEventPayloadAnyOf52Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf52Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf52Properties:
        """Test GlobalEventPayloadAnyOf52Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf52Properties`
        """
        model = GlobalEventPayloadAnyOf52Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf52Properties(
                id = ''
            )
        else:
            return GlobalEventPayloadAnyOf52Properties(
                id = '',
        )
        """

    def testGlobalEventPayloadAnyOf52Properties(self):
        """Test GlobalEventPayloadAnyOf52Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
