# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of60 import GlobalEventPayloadAnyOf60

class TestGlobalEventPayloadAnyOf60(unittest.TestCase):
    """GlobalEventPayloadAnyOf60 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf60:
        """Test GlobalEventPayloadAnyOf60
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf60`
        """
        model = GlobalEventPayloadAnyOf60()
        if include_optional:
            return GlobalEventPayloadAnyOf60(
                id = 'evt_',
                type = 'question.v2.replied',
                properties = opencode_sdk.models.global_event_payload_any_of_60_properties.GlobalEvent_payload_anyOf_60_properties(
                    session_id = 'ses', 
                    request_id = 'que', 
                    answers = [
                        [
                            ''
                            ]
                        ], )
            )
        else:
            return GlobalEventPayloadAnyOf60(
                id = 'evt_',
                type = 'question.v2.replied',
                properties = opencode_sdk.models.global_event_payload_any_of_60_properties.GlobalEvent_payload_anyOf_60_properties(
                    session_id = 'ses', 
                    request_id = 'que', 
                    answers = [
                        [
                            ''
                            ]
                        ], ),
        )
        """

    def testGlobalEventPayloadAnyOf60(self):
        """Test GlobalEventPayloadAnyOf60"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
