# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.v2_pty_create200_response import V2PtyCreate200Response

class TestV2PtyCreate200Response(unittest.TestCase):
    """V2PtyCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2PtyCreate200Response:
        """Test V2PtyCreate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2PtyCreate200Response`
        """
        model = V2PtyCreate200Response()
        if include_optional:
            return V2PtyCreate200Response(
                location = opencode_sdk.models.location_info.LocationInfo(
                    directory = '', 
                    workspace_id = 'wrk', 
                    project = opencode_sdk.models.location_info_project.LocationInfo_project(
                        id = '', 
                        directory = '', ), ),
                data = opencode_sdk.models.pty.Pty(
                    id = 'pty', 
                    title = '', 
                    command = '', 
                    args = [
                        ''
                        ], 
                    cwd = '', 
                    status = 'running', 
                    pid = 0, 
                    exit_code = 0, )
            )
        else:
            return V2PtyCreate200Response(
                location = opencode_sdk.models.location_info.LocationInfo(
                    directory = '', 
                    workspace_id = 'wrk', 
                    project = opencode_sdk.models.location_info_project.LocationInfo_project(
                        id = '', 
                        directory = '', ), ),
                data = opencode_sdk.models.pty.Pty(
                    id = 'pty', 
                    title = '', 
                    command = '', 
                    args = [
                        ''
                        ], 
                    cwd = '', 
                    status = 'running', 
                    pid = 0, 
                    exit_code = 0, ),
        )
        """

    def testV2PtyCreate200Response(self):
        """Test V2PtyCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
