# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of34_properties import GlobalEventPayloadAnyOf34Properties

class TestGlobalEventPayloadAnyOf34Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf34Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf34Properties:
        """Test GlobalEventPayloadAnyOf34Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf34Properties`
        """
        model = GlobalEventPayloadAnyOf34Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf34Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                call_id = '',
                structured = opencode_sdk.models.metadata.metadata(),
                content = [
                    null
                    ],
                output_paths = [
                    ''
                    ],
                result = None,
                provider = opencode_sdk.models.global_event_payload_any_of_32_properties_provider.GlobalEvent_payload_anyOf_32_properties_provider(
                    executed = True, 
                    metadata = {
                        'key' : None
                        }, )
            )
        else:
            return GlobalEventPayloadAnyOf34Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                call_id = '',
                structured = opencode_sdk.models.metadata.metadata(),
                content = [
                    null
                    ],
                provider = opencode_sdk.models.global_event_payload_any_of_32_properties_provider.GlobalEvent_payload_anyOf_32_properties_provider(
                    executed = True, 
                    metadata = {
                        'key' : None
                        }, ),
        )
        """

    def testGlobalEventPayloadAnyOf34Properties(self):
        """Test GlobalEventPayloadAnyOf34Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
