# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of29 import GlobalEventPayloadAnyOf29

class TestGlobalEventPayloadAnyOf29(unittest.TestCase):
    """GlobalEventPayloadAnyOf29 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf29:
        """Test GlobalEventPayloadAnyOf29
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf29`
        """
        model = GlobalEventPayloadAnyOf29()
        if include_optional:
            return GlobalEventPayloadAnyOf29(
                id = 'evt_',
                type = 'session.next.tool.input.started',
                properties = opencode_sdk.models.global_event_payload_any_of_29_properties.GlobalEvent_payload_anyOf_29_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    call_id = '', 
                    name = '', )
            )
        else:
            return GlobalEventPayloadAnyOf29(
                id = 'evt_',
                type = 'session.next.tool.input.started',
                properties = opencode_sdk.models.global_event_payload_any_of_29_properties.GlobalEvent_payload_anyOf_29_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    call_id = '', 
                    name = '', ),
        )
        """

    def testGlobalEventPayloadAnyOf29(self):
        """Test GlobalEventPayloadAnyOf29"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
