# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.model_v2_info_variants_inner import ModelV2InfoVariantsInner

class TestModelV2InfoVariantsInner(unittest.TestCase):
    """ModelV2InfoVariantsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelV2InfoVariantsInner:
        """Test ModelV2InfoVariantsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelV2InfoVariantsInner`
        """
        model = ModelV2InfoVariantsInner()
        if include_optional:
            return ModelV2InfoVariantsInner(
                id = '',
                headers = {
                    'key' : ''
                    },
                body = opencode_sdk.models.metadata.metadata()
            )
        else:
            return ModelV2InfoVariantsInner(
                id = '',
                headers = {
                    'key' : ''
                    },
                body = opencode_sdk.models.metadata.metadata(),
        )
        """

    def testModelV2InfoVariantsInner(self):
        """Test ModelV2InfoVariantsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
