# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.app_skills200_response_inner import AppSkills200ResponseInner

class TestAppSkills200ResponseInner(unittest.TestCase):
    """AppSkills200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppSkills200ResponseInner:
        """Test AppSkills200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppSkills200ResponseInner`
        """
        model = AppSkills200ResponseInner()
        if include_optional:
            return AppSkills200ResponseInner(
                name = '',
                description = '',
                location = '',
                content = ''
            )
        else:
            return AppSkills200ResponseInner(
                name = '',
                location = '',
                content = '',
        )
        """

    def testAppSkills200ResponseInner(self):
        """Test AppSkills200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
