# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_next_revert_cleared import SessionNextRevertCleared

class TestSessionNextRevertCleared(unittest.TestCase):
    """SessionNextRevertCleared unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionNextRevertCleared:
        """Test SessionNextRevertCleared
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionNextRevertCleared`
        """
        model = SessionNextRevertCleared()
        if include_optional:
            return SessionNextRevertCleared(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'session.next.revert.cleared',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', )
            )
        else:
            return SessionNextRevertCleared(
                id = 'evt_',
                type = 'session.next.revert.cleared',
                data = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', ),
        )
        """

    def testSessionNextRevertCleared(self):
        """Test SessionNextRevertCleared"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
