# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.output_format1_any_of import OutputFormat1AnyOf

class TestOutputFormat1AnyOf(unittest.TestCase):
    """OutputFormat1AnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputFormat1AnyOf:
        """Test OutputFormat1AnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputFormat1AnyOf`
        """
        model = OutputFormat1AnyOf()
        if include_optional:
            return OutputFormat1AnyOf(
                type = 'text'
            )
        else:
            return OutputFormat1AnyOf(
                type = 'text',
        )
        """

    def testOutputFormat1AnyOf(self):
        """Test OutputFormat1AnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
