# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_v2_info import ProviderV2Info

class TestProviderV2Info(unittest.TestCase):
    """ProviderV2Info unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderV2Info:
        """Test ProviderV2Info
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderV2Info`
        """
        model = ProviderV2Info()
        if include_optional:
            return ProviderV2Info(
                id = '',
                integration_id = '',
                name = '',
                disabled = True,
                api = None,
                request = opencode_sdk.models.provider_request.ProviderRequest(
                    headers = {
                        'key' : ''
                        }, 
                    body = opencode_sdk.models.body.body(), )
            )
        else:
            return ProviderV2Info(
                id = '',
                name = '',
                api = None,
                request = opencode_sdk.models.provider_request.ProviderRequest(
                    headers = {
                        'key' : ''
                        }, 
                    body = opencode_sdk.models.body.body(), ),
        )
        """

    def testProviderV2Info(self):
        """Test ProviderV2Info"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
