# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_event_session_next_synthetic import SyncEventSessionNextSynthetic

class TestSyncEventSessionNextSynthetic(unittest.TestCase):
    """SyncEventSessionNextSynthetic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncEventSessionNextSynthetic:
        """Test SyncEventSessionNextSynthetic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncEventSessionNextSynthetic`
        """
        model = SyncEventSessionNextSynthetic()
        if include_optional:
            return SyncEventSessionNextSynthetic(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_session_next_synthetic_sync_event.SyncEventSessionNextSynthetic_syncEvent(
                    type = 'session.next.synthetic.1', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_16_properties.GlobalEvent_payload_anyOf_16_properties(
                        timestamp = 1.337, 
                        session_id = 'ses', 
                        message_id = 'msg_', 
                        text = '', ), )
            )
        else:
            return SyncEventSessionNextSynthetic(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_session_next_synthetic_sync_event.SyncEventSessionNextSynthetic_syncEvent(
                    type = 'session.next.synthetic.1', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_16_properties.GlobalEvent_payload_anyOf_16_properties(
                        timestamp = 1.337, 
                        session_id = 'ses', 
                        message_id = 'msg_', 
                        text = '', ), ),
        )
        """

    def testSyncEventSessionNextSynthetic(self):
        """Test SyncEventSessionNextSynthetic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
