# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_message_assistant_tool_state import SessionMessageAssistantToolState

class TestSessionMessageAssistantToolState(unittest.TestCase):
    """SessionMessageAssistantToolState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionMessageAssistantToolState:
        """Test SessionMessageAssistantToolState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionMessageAssistantToolState`
        """
        model = SessionMessageAssistantToolState()
        if include_optional:
            return SessionMessageAssistantToolState(
                status = 'error',
                input = opencode_sdk.models.input.input(),
                structured = opencode_sdk.models.structured.structured(),
                content = [
                    null
                    ],
                attachments = [
                    opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                        uri = '', 
                        mime = '', 
                        name = '', 
                        description = '', 
                        source = opencode_sdk.models.prompt_source.PromptSource(
                            start = 1.337, 
                            end = 1.337, 
                            text = '', ), )
                    ],
                output_paths = [
                    ''
                    ],
                result = None,
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', )
            )
        else:
            return SessionMessageAssistantToolState(
                status = 'error',
                input = opencode_sdk.models.input.input(),
                structured = opencode_sdk.models.structured.structured(),
                content = [
                    null
                    ],
                error = opencode_sdk.models.session_error_unknown.SessionErrorUnknown(
                    type = 'unknown', 
                    message = '', ),
        )
        """

    def testSessionMessageAssistantToolState(self):
        """Test SessionMessageAssistantToolState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
