# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of86 import GlobalEventPayloadAnyOf86

class TestGlobalEventPayloadAnyOf86(unittest.TestCase):
    """GlobalEventPayloadAnyOf86 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf86:
        """Test GlobalEventPayloadAnyOf86
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf86`
        """
        model = GlobalEventPayloadAnyOf86()
        if include_optional:
            return GlobalEventPayloadAnyOf86(
                id = 'evt_',
                type = 'server.connected',
                properties = opencode_sdk.models.data.data()
            )
        else:
            return GlobalEventPayloadAnyOf86(
                id = 'evt_',
                type = 'server.connected',
                properties = opencode_sdk.models.data.data(),
        )
        """

    def testGlobalEventPayloadAnyOf86(self):
        """Test GlobalEventPayloadAnyOf86"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
