# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_event_session_next_text_ended_sync_event import SyncEventSessionNextTextEndedSyncEvent

class TestSyncEventSessionNextTextEndedSyncEvent(unittest.TestCase):
    """SyncEventSessionNextTextEndedSyncEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncEventSessionNextTextEndedSyncEvent:
        """Test SyncEventSessionNextTextEndedSyncEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncEventSessionNextTextEndedSyncEvent`
        """
        model = SyncEventSessionNextTextEndedSyncEvent()
        if include_optional:
            return SyncEventSessionNextTextEndedSyncEvent(
                type = 'session.next.text.ended.1',
                id = 'evt_',
                seq = 1.337,
                aggregate_id = '',
                data = opencode_sdk.models.global_event_payload_any_of_25_properties.GlobalEvent_payload_anyOf_25_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    text_id = '', 
                    text = '', )
            )
        else:
            return SyncEventSessionNextTextEndedSyncEvent(
                type = 'session.next.text.ended.1',
                id = 'evt_',
                seq = 1.337,
                aggregate_id = '',
                data = opencode_sdk.models.global_event_payload_any_of_25_properties.GlobalEvent_payload_anyOf_25_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    text_id = '', 
                    text = '', ),
        )
        """

    def testSyncEventSessionNextTextEndedSyncEvent(self):
        """Test SyncEventSessionNextTextEndedSyncEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
