# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.tool_state_running_time import ToolStateRunningTime

class TestToolStateRunningTime(unittest.TestCase):
    """ToolStateRunningTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolStateRunningTime:
        """Test ToolStateRunningTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolStateRunningTime`
        """
        model = ToolStateRunningTime()
        if include_optional:
            return ToolStateRunningTime(
                start = 0
            )
        else:
            return ToolStateRunningTime(
                start = 0,
        )
        """

    def testToolStateRunningTime(self):
        """Test ToolStateRunningTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
