# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.api.sync_api import SyncApi


class TestSyncApi(unittest.IsolatedAsyncioTestCase):
    """SyncApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SyncApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_sync_history_list(self) -> None:
        """Test case for sync_history_list

        List sync events
        """
        pass

    def test_sync_history_list_sync(self) -> None:
        """Test case for sync_history_list (synchronous)

        List sync events
        """
        pass

    async def test_sync_replay(self) -> None:
        """Test case for sync_replay

        Replay sync events
        """
        pass

    def test_sync_replay_sync(self) -> None:
        """Test case for sync_replay (synchronous)

        Replay sync events
        """
        pass

    async def test_sync_start(self) -> None:
        """Test case for sync_start

        Start workspace sync
        """
        pass

    def test_sync_start_sync(self) -> None:
        """Test case for sync_start (synchronous)

        Start workspace sync
        """
        pass

    async def test_sync_steal(self) -> None:
        """Test case for sync_steal

        Steal session into workspace
        """
        pass

    def test_sync_steal_sync(self) -> None:
        """Test case for sync_steal (synchronous)

        Steal session into workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
