# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_session_next_tool_progress import EventSessionNextToolProgress

class TestEventSessionNextToolProgress(unittest.TestCase):
    """EventSessionNextToolProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventSessionNextToolProgress:
        """Test EventSessionNextToolProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventSessionNextToolProgress`
        """
        model = EventSessionNextToolProgress()
        if include_optional:
            return EventSessionNextToolProgress(
                id = 'evt_',
                type = 'session.next.tool.progress',
                properties = opencode_sdk.models.global_event_payload_any_of_33_properties.GlobalEvent_payload_anyOf_33_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    call_id = '', 
                    structured = opencode_sdk.models.metadata.metadata(), 
                    content = [
                        null
                        ], )
            )
        else:
            return EventSessionNextToolProgress(
                id = 'evt_',
                type = 'session.next.tool.progress',
                properties = opencode_sdk.models.global_event_payload_any_of_33_properties.GlobalEvent_payload_anyOf_33_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    assistant_message_id = 'msg_', 
                    call_id = '', 
                    structured = opencode_sdk.models.metadata.metadata(), 
                    content = [
                        null
                        ], ),
        )
        """

    def testEventSessionNextToolProgress(self):
        """Test EventSessionNextToolProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
