# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_catalog_updated import EventCatalogUpdated

class TestEventCatalogUpdated(unittest.TestCase):
    """EventCatalogUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventCatalogUpdated:
        """Test EventCatalogUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventCatalogUpdated`
        """
        model = EventCatalogUpdated()
        if include_optional:
            return EventCatalogUpdated(
                id = 'evt_',
                type = 'catalog.updated',
                properties = opencode_sdk.models.properties.properties()
            )
        else:
            return EventCatalogUpdated(
                id = 'evt_',
                type = 'catalog.updated',
                properties = opencode_sdk.models.properties.properties(),
        )
        """

    def testEventCatalogUpdated(self):
        """Test EventCatalogUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
