# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.lsp_status import LSPStatus

class TestLSPStatus(unittest.TestCase):
    """LSPStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LSPStatus:
        """Test LSPStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LSPStatus`
        """
        model = LSPStatus()
        if include_optional:
            return LSPStatus(
                id = '',
                name = '',
                root = '',
                status = 'connected'
            )
        else:
            return LSPStatus(
                id = '',
                name = '',
                root = '',
                status = 'connected',
        )
        """

    def testLSPStatus(self):
        """Test LSPStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
