# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_config_models_value_cost_context_over200k import ProviderConfigModelsValueCostContextOver200k

class TestProviderConfigModelsValueCostContextOver200k(unittest.TestCase):
    """ProviderConfigModelsValueCostContextOver200k unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderConfigModelsValueCostContextOver200k:
        """Test ProviderConfigModelsValueCostContextOver200k
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderConfigModelsValueCostContextOver200k`
        """
        model = ProviderConfigModelsValueCostContextOver200k()
        if include_optional:
            return ProviderConfigModelsValueCostContextOver200k(
                input = 1.337,
                output = 1.337,
                cache_read = 1.337,
                cache_write = 1.337
            )
        else:
            return ProviderConfigModelsValueCostContextOver200k(
                input = 1.337,
                output = 1.337,
        )
        """

    def testProviderConfigModelsValueCostContextOver200k(self):
        """Test ProviderConfigModelsValueCostContextOver200k"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
