# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_session_next_compaction_ended import EventSessionNextCompactionEnded

class TestEventSessionNextCompactionEnded(unittest.TestCase):
    """EventSessionNextCompactionEnded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventSessionNextCompactionEnded:
        """Test EventSessionNextCompactionEnded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventSessionNextCompactionEnded`
        """
        model = EventSessionNextCompactionEnded()
        if include_optional:
            return EventSessionNextCompactionEnded(
                id = 'evt_',
                type = 'session.next.compaction.ended',
                properties = opencode_sdk.models.global_event_payload_any_of_39_properties.GlobalEvent_payload_anyOf_39_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    reason = 'auto', 
                    text = '', 
                    recent = '', )
            )
        else:
            return EventSessionNextCompactionEnded(
                id = 'evt_',
                type = 'session.next.compaction.ended',
                properties = opencode_sdk.models.global_event_payload_any_of_39_properties.GlobalEvent_payload_anyOf_39_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    reason = 'auto', 
                    text = '', 
                    recent = '', ),
        )
        """

    def testEventSessionNextCompactionEnded(self):
        """Test EventSessionNextCompactionEnded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
