# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_replay_request_events_inner import SyncReplayRequestEventsInner

class TestSyncReplayRequestEventsInner(unittest.TestCase):
    """SyncReplayRequestEventsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncReplayRequestEventsInner:
        """Test SyncReplayRequestEventsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncReplayRequestEventsInner`
        """
        model = SyncReplayRequestEventsInner()
        if include_optional:
            return SyncReplayRequestEventsInner(
                id = 'evt_',
                aggregate_id = '',
                seq = 0,
                type = '',
                data = opencode_sdk.models.metadata.metadata()
            )
        else:
            return SyncReplayRequestEventsInner(
                id = 'evt_',
                aggregate_id = '',
                seq = 0,
                type = '',
                data = opencode_sdk.models.metadata.metadata(),
        )
        """

    def testSyncReplayRequestEventsInner(self):
        """Test SyncReplayRequestEventsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
