# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.prompt_agent_attachment import PromptAgentAttachment

class TestPromptAgentAttachment(unittest.TestCase):
    """PromptAgentAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptAgentAttachment:
        """Test PromptAgentAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptAgentAttachment`
        """
        model = PromptAgentAttachment()
        if include_optional:
            return PromptAgentAttachment(
                name = '',
                source = opencode_sdk.models.prompt_source.PromptSource(
                    start = 1.337, 
                    end = 1.337, 
                    text = '', )
            )
        else:
            return PromptAgentAttachment(
                name = '',
        )
        """

    def testPromptAgentAttachment(self):
        """Test PromptAgentAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
