# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of75 import GlobalEventPayloadAnyOf75

class TestGlobalEventPayloadAnyOf75(unittest.TestCase):
    """GlobalEventPayloadAnyOf75 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf75:
        """Test GlobalEventPayloadAnyOf75
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf75`
        """
        model = GlobalEventPayloadAnyOf75()
        if include_optional:
            return GlobalEventPayloadAnyOf75(
                id = 'evt_',
                type = 'session.idle',
                properties = opencode_sdk.models.sync_steal_request.sync_steal_request(
                    session_id = 'ses', )
            )
        else:
            return GlobalEventPayloadAnyOf75(
                id = 'evt_',
                type = 'session.idle',
                properties = opencode_sdk.models.sync_steal_request.sync_steal_request(
                    session_id = 'ses', ),
        )
        """

    def testGlobalEventPayloadAnyOf75(self):
        """Test GlobalEventPayloadAnyOf75"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
