# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.config_providers200_response import ConfigProviders200Response

class TestConfigProviders200Response(unittest.TestCase):
    """ConfigProviders200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigProviders200Response:
        """Test ConfigProviders200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigProviders200Response`
        """
        model = ConfigProviders200Response()
        if include_optional:
            return ConfigProviders200Response(
                providers = [
                    opencode_sdk.models.provider.Provider(
                        id = '', 
                        name = '', 
                        source = 'env', 
                        env = [
                            ''
                            ], 
                        key = '', 
                        options = opencode_sdk.models.options.options(), 
                        models = {
                            'key' : opencode_sdk.models.model.Model(
                                id = '', 
                                provider_id = '', 
                                api = opencode_sdk.models.model_api.Model_api(
                                    id = '', 
                                    url = '', 
                                    npm = '', ), 
                                name = '', 
                                family = '', 
                                capabilities = opencode_sdk.models.model_capabilities.Model_capabilities(
                                    temperature = True, 
                                    reasoning = True, 
                                    attachment = True, 
                                    toolcall = True, 
                                    input = opencode_sdk.models.model_capabilities_input.Model_capabilities_input(
                                        text = True, 
                                        audio = True, 
                                        image = True, 
                                        video = True, 
                                        pdf = True, ), 
                                    output = opencode_sdk.models.model_capabilities_input.Model_capabilities_input(
                                        text = True, 
                                        audio = True, 
                                        image = True, 
                                        video = True, 
                                        pdf = True, ), 
                                    interleaved = null, ), 
                                cost = opencode_sdk.models.model_cost.Model_cost(
                                    input = 1.337, 
                                    output = 1.337, 
                                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                        read = 1.337, 
                                        write = 1.337, ), 
                                    tiers = [
                                        opencode_sdk.models.model_cost_tiers_inner.Model_cost_tiers_inner(
                                            input = 1.337, 
                                            output = 1.337, 
                                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                                read = 1.337, 
                                                write = 1.337, ), 
                                            tier = opencode_sdk.models.model_cost_tiers_inner_tier.Model_cost_tiers_inner_tier(
                                                type = 'context', 
                                                size = 1.337, ), )
                                        ], 
                                    experimental_over200_k = opencode_sdk.models.model_cost_experimental_over200_k.Model_cost_experimentalOver200K(
                                        input = 1.337, 
                                        output = 1.337, 
                                        cache = , ), ), 
                                limit = opencode_sdk.models.provider_config_models_value_limit.ProviderConfig_models_value_limit(
                                    context = 1.337, 
                                    output = 1.337, ), 
                                status = 'alpha', 
                                options = opencode_sdk.models.metadata.metadata(), 
                                headers = {
                                    'key' : ''
                                    }, 
                                release_date = '', 
                                variants = {
                                    'key' : None
                                    }, )
                            }, )
                    ],
                default = {
                    'key' : ''
                    }
            )
        else:
            return ConfigProviders200Response(
                providers = [
                    opencode_sdk.models.provider.Provider(
                        id = '', 
                        name = '', 
                        source = 'env', 
                        env = [
                            ''
                            ], 
                        key = '', 
                        options = opencode_sdk.models.options.options(), 
                        models = {
                            'key' : opencode_sdk.models.model.Model(
                                id = '', 
                                provider_id = '', 
                                api = opencode_sdk.models.model_api.Model_api(
                                    id = '', 
                                    url = '', 
                                    npm = '', ), 
                                name = '', 
                                family = '', 
                                capabilities = opencode_sdk.models.model_capabilities.Model_capabilities(
                                    temperature = True, 
                                    reasoning = True, 
                                    attachment = True, 
                                    toolcall = True, 
                                    input = opencode_sdk.models.model_capabilities_input.Model_capabilities_input(
                                        text = True, 
                                        audio = True, 
                                        image = True, 
                                        video = True, 
                                        pdf = True, ), 
                                    output = opencode_sdk.models.model_capabilities_input.Model_capabilities_input(
                                        text = True, 
                                        audio = True, 
                                        image = True, 
                                        video = True, 
                                        pdf = True, ), 
                                    interleaved = null, ), 
                                cost = opencode_sdk.models.model_cost.Model_cost(
                                    input = 1.337, 
                                    output = 1.337, 
                                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                        read = 1.337, 
                                        write = 1.337, ), 
                                    tiers = [
                                        opencode_sdk.models.model_cost_tiers_inner.Model_cost_tiers_inner(
                                            input = 1.337, 
                                            output = 1.337, 
                                            cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                                                read = 1.337, 
                                                write = 1.337, ), 
                                            tier = opencode_sdk.models.model_cost_tiers_inner_tier.Model_cost_tiers_inner_tier(
                                                type = 'context', 
                                                size = 1.337, ), )
                                        ], 
                                    experimental_over200_k = opencode_sdk.models.model_cost_experimental_over200_k.Model_cost_experimentalOver200K(
                                        input = 1.337, 
                                        output = 1.337, 
                                        cache = , ), ), 
                                limit = opencode_sdk.models.provider_config_models_value_limit.ProviderConfig_models_value_limit(
                                    context = 1.337, 
                                    output = 1.337, ), 
                                status = 'alpha', 
                                options = opencode_sdk.models.metadata.metadata(), 
                                headers = {
                                    'key' : ''
                                    }, 
                                release_date = '', 
                                variants = {
                                    'key' : None
                                    }, )
                            }, )
                    ],
                default = {
                    'key' : ''
                    },
        )
        """

    def testConfigProviders200Response(self):
        """Test ConfigProviders200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
