# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.api_error_data import APIErrorData

class TestAPIErrorData(unittest.TestCase):
    """APIErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIErrorData:
        """Test APIErrorData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIErrorData`
        """
        model = APIErrorData()
        if include_optional:
            return APIErrorData(
                message = '',
                status_code = 0,
                is_retryable = True,
                response_headers = {
                    'key' : ''
                    },
                response_body = '',
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return APIErrorData(
                message = '',
                is_retryable = True,
        )
        """

    def testAPIErrorData(self):
        """Test APIErrorData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
