# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.experimental_project_copy_generate_name200_response import ExperimentalProjectCopyGenerateName200Response

class TestExperimentalProjectCopyGenerateName200Response(unittest.TestCase):
    """ExperimentalProjectCopyGenerateName200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExperimentalProjectCopyGenerateName200Response:
        """Test ExperimentalProjectCopyGenerateName200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExperimentalProjectCopyGenerateName200Response`
        """
        model = ExperimentalProjectCopyGenerateName200Response()
        if include_optional:
            return ExperimentalProjectCopyGenerateName200Response(
                name = ''
            )
        else:
            return ExperimentalProjectCopyGenerateName200Response(
                name = '',
        )
        """

    def testExperimentalProjectCopyGenerateName200Response(self):
        """Test ExperimentalProjectCopyGenerateName200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
