# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_config import ProviderConfig

class TestProviderConfig(unittest.TestCase):
    """ProviderConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderConfig:
        """Test ProviderConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderConfig`
        """
        model = ProviderConfig()
        if include_optional:
            return ProviderConfig(
                api = '',
                name = '',
                env = [
                    ''
                    ],
                id = '',
                npm = '',
                whitelist = [
                    ''
                    ],
                blacklist = [
                    ''
                    ],
                options = {
                    'key' : null
                    },
                models = {
                    'key' : opencode_sdk.models.provider_config_models_value.ProviderConfig_models_value(
                        id = '', 
                        name = '', 
                        family = '', 
                        release_date = '', 
                        attachment = True, 
                        reasoning = True, 
                        temperature = True, 
                        tool_call = True, 
                        interleaved = null, 
                        cost = opencode_sdk.models.provider_config_models_value_cost.ProviderConfig_models_value_cost(
                            input = 1.337, 
                            output = 1.337, 
                            cache_read = 1.337, 
                            cache_write = 1.337, 
                            context_over_200k = opencode_sdk.models.provider_config_models_value_cost_context_over_200k.ProviderConfig_models_value_cost_context_over_200k(
                                input = 1.337, 
                                output = 1.337, 
                                cache_read = 1.337, 
                                cache_write = 1.337, ), ), 
                        limit = opencode_sdk.models.provider_config_models_value_limit.ProviderConfig_models_value_limit(
                            context = 1.337, 
                            input = 1.337, 
                            output = 1.337, ), 
                        modalities = opencode_sdk.models.provider_config_models_value_modalities.ProviderConfig_models_value_modalities(
                            input = [
                                'text'
                                ], 
                            output = [
                                'text'
                                ], ), 
                        experimental = True, 
                        status = 'alpha', 
                        provider = opencode_sdk.models.provider_config_models_value_provider.ProviderConfig_models_value_provider(
                            npm = '', 
                            api = '', ), 
                        options = opencode_sdk.models.metadata.metadata(), 
                        headers = {
                            'key' : ''
                            }, 
                        variants = {
                            'key' : {
                                'key' : null
                                }
                            }, )
                    }
            )
        else:
            return ProviderConfig(
        )
        """

    def testProviderConfig(self):
        """Test ProviderConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
