# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_tokens_cache import SessionTokensCache

class TestSessionTokensCache(unittest.TestCase):
    """SessionTokensCache unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionTokensCache:
        """Test SessionTokensCache
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionTokensCache`
        """
        model = SessionTokensCache()
        if include_optional:
            return SessionTokensCache(
                read = 1.337,
                write = 1.337
            )
        else:
            return SessionTokensCache(
                read = 1.337,
                write = 1.337,
        )
        """

    def testSessionTokensCache(self):
        """Test SessionTokensCache"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
