# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of44_properties import GlobalEventPayloadAnyOf44Properties

class TestGlobalEventPayloadAnyOf44Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf44Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf44Properties:
        """Test GlobalEventPayloadAnyOf44Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf44Properties`
        """
        model = GlobalEventPayloadAnyOf44Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf44Properties(
                session_id = 'ses',
                diff = [
                    opencode_sdk.models.snapshot_file_diff.SnapshotFileDiff(
                        file = '', 
                        patch = '', 
                        additions = 1.337, 
                        deletions = 1.337, 
                        status = 'added', )
                    ]
            )
        else:
            return GlobalEventPayloadAnyOf44Properties(
                session_id = 'ses',
                diff = [
                    opencode_sdk.models.snapshot_file_diff.SnapshotFileDiff(
                        file = '', 
                        patch = '', 
                        additions = 1.337, 
                        deletions = 1.337, 
                        status = 'added', )
                    ],
        )
        """

    def testGlobalEventPayloadAnyOf44Properties(self):
        """Test GlobalEventPayloadAnyOf44Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
