# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of77_properties import GlobalEventPayloadAnyOf77Properties

class TestGlobalEventPayloadAnyOf77Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf77Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf77Properties:
        """Test GlobalEventPayloadAnyOf77Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf77Properties`
        """
        model = GlobalEventPayloadAnyOf77Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf77Properties(
                session_id = 'ses',
                request_id = 'que',
                answers = [
                    [
                        ''
                        ]
                    ]
            )
        else:
            return GlobalEventPayloadAnyOf77Properties(
                session_id = 'ses',
                request_id = 'que',
                answers = [
                    [
                        ''
                        ]
                    ],
        )
        """

    def testGlobalEventPayloadAnyOf77Properties(self):
        """Test GlobalEventPayloadAnyOf77Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
