# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of41 import GlobalEventPayloadAnyOf41

class TestGlobalEventPayloadAnyOf41(unittest.TestCase):
    """GlobalEventPayloadAnyOf41 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf41:
        """Test GlobalEventPayloadAnyOf41
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf41`
        """
        model = GlobalEventPayloadAnyOf41()
        if include_optional:
            return GlobalEventPayloadAnyOf41(
                id = 'evt_',
                type = 'session.next.revert.cleared',
                properties = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', )
            )
        else:
            return GlobalEventPayloadAnyOf41(
                id = 'evt_',
                type = 'session.next.revert.cleared',
                properties = opencode_sdk.models.global_event_payload_any_of_41_properties.GlobalEvent_payload_anyOf_41_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', ),
        )
        """

    def testGlobalEventPayloadAnyOf41(self):
        """Test GlobalEventPayloadAnyOf41"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
