# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.v2_session_revert_stage200_response import V2SessionRevertStage200Response

class TestV2SessionRevertStage200Response(unittest.TestCase):
    """V2SessionRevertStage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2SessionRevertStage200Response:
        """Test V2SessionRevertStage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2SessionRevertStage200Response`
        """
        model = V2SessionRevertStage200Response()
        if include_optional:
            return V2SessionRevertStage200Response(
                data = opencode_sdk.models.revert_state.RevertState(
                    message_id = 'msg_', 
                    part_id = '', 
                    snapshot = '', 
                    diff = '', 
                    files = [
                        opencode_sdk.models.file_diff.FileDiff(
                            path = '', 
                            status = 'added', 
                            additions = 0, 
                            deletions = 0, 
                            patch = '', )
                        ], )
            )
        else:
            return V2SessionRevertStage200Response(
                data = opencode_sdk.models.revert_state.RevertState(
                    message_id = 'msg_', 
                    part_id = '', 
                    snapshot = '', 
                    diff = '', 
                    files = [
                        opencode_sdk.models.file_diff.FileDiff(
                            path = '', 
                            status = 'added', 
                            additions = 0, 
                            deletions = 0, 
                            patch = '', )
                        ], ),
        )
        """

    def testV2SessionRevertStage200Response(self):
        """Test V2SessionRevertStage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
