# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.event_session_next_retried import EventSessionNextRetried

class TestEventSessionNextRetried(unittest.TestCase):
    """EventSessionNextRetried unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventSessionNextRetried:
        """Test EventSessionNextRetried
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventSessionNextRetried`
        """
        model = EventSessionNextRetried()
        if include_optional:
            return EventSessionNextRetried(
                id = 'evt_',
                type = 'session.next.retried',
                properties = opencode_sdk.models.global_event_payload_any_of_36_properties.GlobalEvent_payload_anyOf_36_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    attempt = 1.337, 
                    error = opencode_sdk.models.session_next_retry_error.SessionNextRetry_error(
                        message = '', 
                        status_code = 1.337, 
                        is_retryable = True, 
                        response_headers = {
                            'key' : ''
                            }, 
                        response_body = '', 
                        metadata = {
                            'key' : ''
                            }, ), )
            )
        else:
            return EventSessionNextRetried(
                id = 'evt_',
                type = 'session.next.retried',
                properties = opencode_sdk.models.global_event_payload_any_of_36_properties.GlobalEvent_payload_anyOf_36_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    attempt = 1.337, 
                    error = opencode_sdk.models.session_next_retry_error.SessionNextRetry_error(
                        message = '', 
                        status_code = 1.337, 
                        is_retryable = True, 
                        response_headers = {
                            'key' : ''
                            }, 
                        response_body = '', 
                        metadata = {
                            'key' : ''
                            }, ), ),
        )
        """

    def testEventSessionNextRetried(self):
        """Test EventSessionNextRetried"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
