# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.experimental_console_switch_org_request import ExperimentalConsoleSwitchOrgRequest

class TestExperimentalConsoleSwitchOrgRequest(unittest.TestCase):
    """ExperimentalConsoleSwitchOrgRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExperimentalConsoleSwitchOrgRequest:
        """Test ExperimentalConsoleSwitchOrgRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExperimentalConsoleSwitchOrgRequest`
        """
        model = ExperimentalConsoleSwitchOrgRequest()
        if include_optional:
            return ExperimentalConsoleSwitchOrgRequest(
                account_id = '',
                org_id = ''
            )
        else:
            return ExperimentalConsoleSwitchOrgRequest(
                account_id = '',
                org_id = '',
        )
        """

    def testExperimentalConsoleSwitchOrgRequest(self):
        """Test ExperimentalConsoleSwitchOrgRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
