# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of45_properties import GlobalEventPayloadAnyOf45Properties

class TestGlobalEventPayloadAnyOf45Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf45Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf45Properties:
        """Test GlobalEventPayloadAnyOf45Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf45Properties`
        """
        model = GlobalEventPayloadAnyOf45Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf45Properties(
                session_id = 'ses',
                error = None
            )
        else:
            return GlobalEventPayloadAnyOf45Properties(
        )
        """

    def testGlobalEventPayloadAnyOf45Properties(self):
        """Test GlobalEventPayloadAnyOf45Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
