# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_config_models_value_interleaved_any_of import ProviderConfigModelsValueInterleavedAnyOf

class TestProviderConfigModelsValueInterleavedAnyOf(unittest.TestCase):
    """ProviderConfigModelsValueInterleavedAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderConfigModelsValueInterleavedAnyOf:
        """Test ProviderConfigModelsValueInterleavedAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderConfigModelsValueInterleavedAnyOf`
        """
        model = ProviderConfigModelsValueInterleavedAnyOf()
        if include_optional:
            return ProviderConfigModelsValueInterleavedAnyOf(
                var_field = 'reasoning'
            )
        else:
            return ProviderConfigModelsValueInterleavedAnyOf(
                var_field = 'reasoning',
        )
        """

    def testProviderConfigModelsValueInterleavedAnyOf(self):
        """Test ProviderConfigModelsValueInterleavedAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
