# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_next_agent_switched import SessionNextAgentSwitched

class TestSessionNextAgentSwitched(unittest.TestCase):
    """SessionNextAgentSwitched unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionNextAgentSwitched:
        """Test SessionNextAgentSwitched
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionNextAgentSwitched`
        """
        model = SessionNextAgentSwitched()
        if include_optional:
            return SessionNextAgentSwitched(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'session.next.agent.switched',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.global_event_payload_any_of_11_properties.GlobalEvent_payload_anyOf_11_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    agent = '', )
            )
        else:
            return SessionNextAgentSwitched(
                id = 'evt_',
                type = 'session.next.agent.switched',
                data = opencode_sdk.models.global_event_payload_any_of_11_properties.GlobalEvent_payload_anyOf_11_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    agent = '', ),
        )
        """

    def testSessionNextAgentSwitched(self):
        """Test SessionNextAgentSwitched"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
