# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.project_copy_error_data import ProjectCopyErrorData

class TestProjectCopyErrorData(unittest.TestCase):
    """ProjectCopyErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCopyErrorData:
        """Test ProjectCopyErrorData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCopyErrorData`
        """
        model = ProjectCopyErrorData()
        if include_optional:
            return ProjectCopyErrorData(
                message = '',
                force_required = True
            )
        else:
            return ProjectCopyErrorData(
                message = '',
        )
        """

    def testProjectCopyErrorData(self):
        """Test ProjectCopyErrorData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
