# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.permission_v2_replied import PermissionV2Replied

class TestPermissionV2Replied(unittest.TestCase):
    """PermissionV2Replied unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionV2Replied:
        """Test PermissionV2Replied
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionV2Replied`
        """
        model = PermissionV2Replied()
        if include_optional:
            return PermissionV2Replied(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'permission.v2.replied',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.global_event_payload_any_of_51_properties.GlobalEvent_payload_anyOf_51_properties(
                    session_id = 'ses', 
                    request_id = 'per', 
                    reply = 'once', )
            )
        else:
            return PermissionV2Replied(
                id = 'evt_',
                type = 'permission.v2.replied',
                data = opencode_sdk.models.global_event_payload_any_of_51_properties.GlobalEvent_payload_anyOf_51_properties(
                    session_id = 'ses', 
                    request_id = 'per', 
                    reply = 'once', ),
        )
        """

    def testPermissionV2Replied(self):
        """Test PermissionV2Replied"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
