# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.output_format1_any_of1 import OutputFormat1AnyOf1

class TestOutputFormat1AnyOf1(unittest.TestCase):
    """OutputFormat1AnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputFormat1AnyOf1:
        """Test OutputFormat1AnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputFormat1AnyOf1`
        """
        model = OutputFormat1AnyOf1()
        if include_optional:
            return OutputFormat1AnyOf1(
                type = 'json_schema',
                var_schema = opencode_sdk.models.metadata.metadata(),
                retry_count = 0
            )
        else:
            return OutputFormat1AnyOf1(
                type = 'json_schema',
                var_schema = opencode_sdk.models.metadata.metadata(),
        )
        """

    def testOutputFormat1AnyOf1(self):
        """Test OutputFormat1AnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
