# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.experimental_workspace_create400_response import ExperimentalWorkspaceCreate400Response

class TestExperimentalWorkspaceCreate400Response(unittest.TestCase):
    """ExperimentalWorkspaceCreate400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExperimentalWorkspaceCreate400Response:
        """Test ExperimentalWorkspaceCreate400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExperimentalWorkspaceCreate400Response`
        """
        model = ExperimentalWorkspaceCreate400Response()
        if include_optional:
            return ExperimentalWorkspaceCreate400Response(
                name = 'WorkspaceCreateError',
                data = opencode_sdk.models.move_session_error_data.MoveSessionError_data(
                    message = '', ),
                tag = 'InvalidRequestError',
                message = '',
                kind = '',
                var_field = ''
            )
        else:
            return ExperimentalWorkspaceCreate400Response(
                name = 'WorkspaceCreateError',
                data = opencode_sdk.models.move_session_error_data.MoveSessionError_data(
                    message = '', ),
                tag = 'InvalidRequestError',
                message = '',
        )
        """

    def testExperimentalWorkspaceCreate400Response(self):
        """Test ExperimentalWorkspaceCreate400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
