# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of73_properties import GlobalEventPayloadAnyOf73Properties

class TestGlobalEventPayloadAnyOf73Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf73Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf73Properties:
        """Test GlobalEventPayloadAnyOf73Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf73Properties`
        """
        model = GlobalEventPayloadAnyOf73Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf73Properties(
                id = '',
                worktree = '',
                vcs = 'git',
                name = '',
                icon = opencode_sdk.models.project_icon.ProjectIcon(
                    url = '', 
                    override = '', 
                    color = '', ),
                commands = opencode_sdk.models.project_commands.ProjectCommands(
                    start = '', ),
                time = opencode_sdk.models.project_time.ProjectTime(
                    created = 0, 
                    updated = 0, 
                    initialized = 0, ),
                sandboxes = [
                    ''
                    ]
            )
        else:
            return GlobalEventPayloadAnyOf73Properties(
                id = '',
                worktree = '',
                time = opencode_sdk.models.project_time.ProjectTime(
                    created = 0, 
                    updated = 0, 
                    initialized = 0, ),
                sandboxes = [
                    ''
                    ],
        )
        """

    def testGlobalEventPayloadAnyOf73Properties(self):
        """Test GlobalEventPayloadAnyOf73Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
