# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_revert import SessionRevert

class TestSessionRevert(unittest.TestCase):
    """SessionRevert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionRevert:
        """Test SessionRevert
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionRevert`
        """
        model = SessionRevert()
        if include_optional:
            return SessionRevert(
                message_id = 'msg',
                part_id = 'prt',
                snapshot = '',
                diff = ''
            )
        else:
            return SessionRevert(
                message_id = 'msg',
        )
        """

    def testSessionRevert(self):
        """Test SessionRevert"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
