# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.config_v2_reference_local import ConfigV2ReferenceLocal

class TestConfigV2ReferenceLocal(unittest.TestCase):
    """ConfigV2ReferenceLocal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigV2ReferenceLocal:
        """Test ConfigV2ReferenceLocal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigV2ReferenceLocal`
        """
        model = ConfigV2ReferenceLocal()
        if include_optional:
            return ConfigV2ReferenceLocal(
                path = '',
                description = '',
                hidden = True
            )
        else:
            return ConfigV2ReferenceLocal(
                path = '',
        )
        """

    def testConfigV2ReferenceLocal(self):
        """Test ConfigV2ReferenceLocal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
