# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.workspace_time_used import WorkspaceTimeUsed

class TestWorkspaceTimeUsed(unittest.TestCase):
    """WorkspaceTimeUsed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceTimeUsed:
        """Test WorkspaceTimeUsed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceTimeUsed`
        """
        model = WorkspaceTimeUsed()
        if include_optional:
            return WorkspaceTimeUsed(
            )
        else:
            return WorkspaceTimeUsed(
        )
        """

    def testWorkspaceTimeUsed(self):
        """Test WorkspaceTimeUsed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
