# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.tui_toast_show import TuiToastShow

class TestTuiToastShow(unittest.TestCase):
    """TuiToastShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuiToastShow:
        """Test TuiToastShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuiToastShow`
        """
        model = TuiToastShow()
        if include_optional:
            return TuiToastShow(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'tui.toast.show',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.tui_show_toast_request.tui_showToast_request(
                    title = '', 
                    message = '', 
                    variant = 'info', 
                    duration = 0, )
            )
        else:
            return TuiToastShow(
                id = 'evt_',
                type = 'tui.toast.show',
                data = opencode_sdk.models.tui_show_toast_request.tui_showToast_request(
                    title = '', 
                    message = '', 
                    variant = 'info', 
                    duration = 0, ),
        )
        """

    def testTuiToastShow(self):
        """Test TuiToastShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
