# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.provider_auth_error1 import ProviderAuthError1

class TestProviderAuthError1(unittest.TestCase):
    """ProviderAuthError1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderAuthError1:
        """Test ProviderAuthError1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderAuthError1`
        """
        model = ProviderAuthError1()
        if include_optional:
            return ProviderAuthError1(
                name = 'BadRequest',
                data = opencode_sdk.models.provider_auth_error1_data.ProviderAuthError1_data(
                    provider_id = '', 
                    field = '', 
                    message = '', 
                    kind = '', )
            )
        else:
            return ProviderAuthError1(
                name = 'BadRequest',
                data = opencode_sdk.models.provider_auth_error1_data.ProviderAuthError1_data(
                    provider_id = '', 
                    field = '', 
                    message = '', 
                    kind = '', ),
        )
        """

    def testProviderAuthError1(self):
        """Test ProviderAuthError1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
