# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_v2_info import SessionV2Info

class TestSessionV2Info(unittest.TestCase):
    """SessionV2Info unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionV2Info:
        """Test SessionV2Info
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionV2Info`
        """
        model = SessionV2Info()
        if include_optional:
            return SessionV2Info(
                id = 'ses',
                parent_id = 'ses',
                project_id = '',
                agent = '',
                model = opencode_sdk.models.session_create_request_model.session_create_request_model(
                    id = '', 
                    provider_id = '', 
                    variant = '', ),
                cost = 1.337,
                tokens = opencode_sdk.models.session_tokens.Session_tokens(
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), ),
                time = opencode_sdk.models.session_v2_info_time.SessionV2Info_time(
                    created = 1.337, 
                    updated = 1.337, 
                    archived = 1.337, ),
                title = '',
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                subpath = '',
                revert = opencode_sdk.models.revert_state.RevertState(
                    message_id = 'msg_', 
                    part_id = '', 
                    snapshot = '', 
                    diff = '', 
                    files = [
                        opencode_sdk.models.file_diff.FileDiff(
                            path = '', 
                            status = 'added', 
                            additions = 0, 
                            deletions = 0, 
                            patch = '', )
                        ], )
            )
        else:
            return SessionV2Info(
                id = 'ses',
                project_id = '',
                cost = 1.337,
                tokens = opencode_sdk.models.session_tokens.Session_tokens(
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), ),
                time = opencode_sdk.models.session_v2_info_time.SessionV2Info_time(
                    created = 1.337, 
                    updated = 1.337, 
                    archived = 1.337, ),
                title = '',
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
        )
        """

    def testSessionV2Info(self):
        """Test SessionV2Info"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
