# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.question_v2_tool import QuestionV2Tool

class TestQuestionV2Tool(unittest.TestCase):
    """QuestionV2Tool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuestionV2Tool:
        """Test QuestionV2Tool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuestionV2Tool`
        """
        model = QuestionV2Tool()
        if include_optional:
            return QuestionV2Tool(
                message_id = '',
                call_id = ''
            )
        else:
            return QuestionV2Tool(
                message_id = '',
                call_id = '',
        )
        """

    def testQuestionV2Tool(self):
        """Test QuestionV2Tool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
