# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.permission_v2_source import PermissionV2Source

class TestPermissionV2Source(unittest.TestCase):
    """PermissionV2Source unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionV2Source:
        """Test PermissionV2Source
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionV2Source`
        """
        model = PermissionV2Source()
        if include_optional:
            return PermissionV2Source(
                type = 'tool',
                message_id = '',
                call_id = ''
            )
        else:
            return PermissionV2Source(
                type = 'tool',
                message_id = '',
                call_id = '',
        )
        """

    def testPermissionV2Source(self):
        """Test PermissionV2Source"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
