# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.tool_state_completed import ToolStateCompleted

class TestToolStateCompleted(unittest.TestCase):
    """ToolStateCompleted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolStateCompleted:
        """Test ToolStateCompleted
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolStateCompleted`
        """
        model = ToolStateCompleted()
        if include_optional:
            return ToolStateCompleted(
                status = 'completed',
                input = opencode_sdk.models.metadata.metadata(),
                output = '',
                title = '',
                metadata = opencode_sdk.models.metadata.metadata(),
                time = opencode_sdk.models.tool_state_completed_time.ToolStateCompleted_time(
                    start = 0, 
                    end = 0, 
                    compacted = 0, ),
                attachments = [
                    opencode_sdk.models.file_part.FilePart(
                        id = 'prt', 
                        session_id = 'ses', 
                        message_id = 'msg', 
                        type = 'file', 
                        mime = '', 
                        filename = '', 
                        url = '', 
                        source = null, )
                    ]
            )
        else:
            return ToolStateCompleted(
                status = 'completed',
                input = opencode_sdk.models.metadata.metadata(),
                output = '',
                title = '',
                metadata = opencode_sdk.models.metadata.metadata(),
                time = opencode_sdk.models.tool_state_completed_time.ToolStateCompleted_time(
                    start = 0, 
                    end = 0, 
                    compacted = 0, ),
        )
        """

    def testToolStateCompleted(self):
        """Test ToolStateCompleted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
