# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.step_finish_part import StepFinishPart

class TestStepFinishPart(unittest.TestCase):
    """StepFinishPart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StepFinishPart:
        """Test StepFinishPart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StepFinishPart`
        """
        model = StepFinishPart()
        if include_optional:
            return StepFinishPart(
                id = 'prt',
                session_id = 'ses',
                message_id = 'msg',
                type = 'step-finish',
                reason = '',
                snapshot = '',
                cost = 1.337,
                tokens = opencode_sdk.models.assistant_message_tokens.AssistantMessage_tokens(
                    total = 1.337, 
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), )
            )
        else:
            return StepFinishPart(
                id = 'prt',
                session_id = 'ses',
                message_id = 'msg',
                type = 'step-finish',
                reason = '',
                cost = 1.337,
                tokens = opencode_sdk.models.assistant_message_tokens.AssistantMessage_tokens(
                    total = 1.337, 
                    input = 1.337, 
                    output = 1.337, 
                    reasoning = 1.337, 
                    cache = opencode_sdk.models.session_tokens_cache.Session_tokens_cache(
                        read = 1.337, 
                        write = 1.337, ), ),
        )
        """

    def testStepFinishPart(self):
        """Test StepFinishPart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
