# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_next_prompted import SessionNextPrompted

class TestSessionNextPrompted(unittest.TestCase):
    """SessionNextPrompted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionNextPrompted:
        """Test SessionNextPrompted
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionNextPrompted`
        """
        model = SessionNextPrompted()
        if include_optional:
            return SessionNextPrompted(
                id = 'evt_',
                metadata = opencode_sdk.models.metadata.metadata(),
                type = 'session.next.prompted',
                durable = opencode_sdk.models.session_status_durable.session_status_durable(
                    aggregate_id = '', 
                    seq = 56, 
                    version = 56, ),
                location = opencode_sdk.models.location_ref.LocationRef(
                    directory = '', 
                    workspace_id = 'wrk', ),
                data = opencode_sdk.models.global_event_payload_any_of_14_properties.GlobalEvent_payload_anyOf_14_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    prompt = opencode_sdk.models.prompt.Prompt(
                        text = '', 
                        files = [
                            opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                                uri = '', 
                                mime = '', 
                                name = '', 
                                description = '', 
                                source = opencode_sdk.models.prompt_source.PromptSource(
                                    start = 1.337, 
                                    end = 1.337, 
                                    text = '', ), )
                            ], 
                        agents = [
                            opencode_sdk.models.prompt_agent_attachment.PromptAgentAttachment(
                                name = '', )
                            ], ), 
                    delivery = 'steer', )
            )
        else:
            return SessionNextPrompted(
                id = 'evt_',
                type = 'session.next.prompted',
                data = opencode_sdk.models.global_event_payload_any_of_14_properties.GlobalEvent_payload_anyOf_14_properties(
                    timestamp = 1.337, 
                    session_id = 'ses', 
                    message_id = 'msg_', 
                    prompt = opencode_sdk.models.prompt.Prompt(
                        text = '', 
                        files = [
                            opencode_sdk.models.prompt_file_attachment.PromptFileAttachment(
                                uri = '', 
                                mime = '', 
                                name = '', 
                                description = '', 
                                source = opencode_sdk.models.prompt_source.PromptSource(
                                    start = 1.337, 
                                    end = 1.337, 
                                    text = '', ), )
                            ], 
                        agents = [
                            opencode_sdk.models.prompt_agent_attachment.PromptAgentAttachment(
                                name = '', )
                            ], ), 
                    delivery = 'steer', ),
        )
        """

    def testSessionNextPrompted(self):
        """Test SessionNextPrompted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
