# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.sync_event_message_part_updated import SyncEventMessagePartUpdated

class TestSyncEventMessagePartUpdated(unittest.TestCase):
    """SyncEventMessagePartUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncEventMessagePartUpdated:
        """Test SyncEventMessagePartUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncEventMessagePartUpdated`
        """
        model = SyncEventMessagePartUpdated()
        if include_optional:
            return SyncEventMessagePartUpdated(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_message_part_updated_sync_event.SyncEventMessagePartUpdated_syncEvent(
                    type = 'message.part.updated.1', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_9_properties.GlobalEvent_payload_anyOf_9_properties(
                        session_id = 'ses', 
                        part = null, 
                        time = 1.337, ), )
            )
        else:
            return SyncEventMessagePartUpdated(
                type = 'sync',
                id = 'evt_',
                sync_event = opencode_sdk.models.sync_event_message_part_updated_sync_event.SyncEventMessagePartUpdated_syncEvent(
                    type = 'message.part.updated.1', 
                    id = 'evt_', 
                    seq = 1.337, 
                    aggregate_id = '', 
                    data = opencode_sdk.models.global_event_payload_any_of_9_properties.GlobalEvent_payload_anyOf_9_properties(
                        session_id = 'ses', 
                        part = null, 
                        time = 1.337, ), ),
        )
        """

    def testSyncEventMessagePartUpdated(self):
        """Test SyncEventMessagePartUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
