# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of9_properties import GlobalEventPayloadAnyOf9Properties

class TestGlobalEventPayloadAnyOf9Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf9Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf9Properties:
        """Test GlobalEventPayloadAnyOf9Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf9Properties`
        """
        model = GlobalEventPayloadAnyOf9Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf9Properties(
                session_id = 'ses',
                part = None,
                time = 1.337
            )
        else:
            return GlobalEventPayloadAnyOf9Properties(
                session_id = 'ses',
                part = None,
                time = 1.337,
        )
        """

    def testGlobalEventPayloadAnyOf9Properties(self):
        """Test GlobalEventPayloadAnyOf9Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
