# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.session_message_model_switched import SessionMessageModelSwitched

class TestSessionMessageModelSwitched(unittest.TestCase):
    """SessionMessageModelSwitched unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionMessageModelSwitched:
        """Test SessionMessageModelSwitched
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionMessageModelSwitched`
        """
        model = SessionMessageModelSwitched()
        if include_optional:
            return SessionMessageModelSwitched(
                id = 'msg_',
                metadata = opencode_sdk.models.metadata.metadata(),
                time = opencode_sdk.models.session_message_agent_switched_time.SessionMessageAgentSwitched_time(
                    created = 1.337, ),
                type = 'model-switched',
                model = opencode_sdk.models.session_create_request_model.session_create_request_model(
                    id = '', 
                    provider_id = '', 
                    variant = '', )
            )
        else:
            return SessionMessageModelSwitched(
                id = 'msg_',
                time = opencode_sdk.models.session_message_agent_switched_time.SessionMessageAgentSwitched_time(
                    created = 1.337, ),
                type = 'model-switched',
                model = opencode_sdk.models.session_create_request_model.session_create_request_model(
                    id = '', 
                    provider_id = '', 
                    variant = '', ),
        )
        """

    def testSessionMessageModelSwitched(self):
        """Test SessionMessageModelSwitched"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
