# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of84 import GlobalEventPayloadAnyOf84

class TestGlobalEventPayloadAnyOf84(unittest.TestCase):
    """GlobalEventPayloadAnyOf84 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf84:
        """Test GlobalEventPayloadAnyOf84
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf84`
        """
        model = GlobalEventPayloadAnyOf84()
        if include_optional:
            return GlobalEventPayloadAnyOf84(
                id = 'evt_',
                type = 'worktree.ready',
                properties = opencode_sdk.models.global_event_payload_any_of_84_properties.GlobalEvent_payload_anyOf_84_properties(
                    name = '', 
                    branch = '', )
            )
        else:
            return GlobalEventPayloadAnyOf84(
                id = 'evt_',
                type = 'worktree.ready',
                properties = opencode_sdk.models.global_event_payload_any_of_84_properties.GlobalEvent_payload_anyOf_84_properties(
                    name = '', 
                    branch = '', ),
        )
        """

    def testGlobalEventPayloadAnyOf84(self):
        """Test GlobalEventPayloadAnyOf84"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
