# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencode_sdk.models.global_event_payload_any_of25_properties import GlobalEventPayloadAnyOf25Properties

class TestGlobalEventPayloadAnyOf25Properties(unittest.TestCase):
    """GlobalEventPayloadAnyOf25Properties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalEventPayloadAnyOf25Properties:
        """Test GlobalEventPayloadAnyOf25Properties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalEventPayloadAnyOf25Properties`
        """
        model = GlobalEventPayloadAnyOf25Properties()
        if include_optional:
            return GlobalEventPayloadAnyOf25Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                text_id = '',
                text = ''
            )
        else:
            return GlobalEventPayloadAnyOf25Properties(
                timestamp = 1.337,
                session_id = 'ses',
                assistant_message_id = 'msg_',
                text_id = '',
                text = '',
        )
        """

    def testGlobalEventPayloadAnyOf25Properties(self):
        """Test GlobalEventPayloadAnyOf25Properties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
