# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from opencode_sdk.models.permission_rule import PermissionRule
from opencode_sdk.models.session_prompt_async_request_model import SessionPromptAsyncRequestModel
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Agent(BaseModel):
    """
    Agent
    """ # noqa: E501
    name: StrictStr
    description: Optional[StrictStr] = None
    mode: StrictStr
    native: Optional[StrictBool] = None
    hidden: Optional[StrictBool] = None
    top_p: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="topP")
    temperature: Optional[Union[StrictFloat, StrictInt]] = None
    color: Optional[StrictStr] = None
    permission: List[PermissionRule]
    model: Optional[SessionPromptAsyncRequestModel] = None
    variant: Optional[StrictStr] = None
    prompt: Optional[StrictStr] = None
    options: Dict[str, Any]
    steps: Optional[Union[StrictFloat, StrictInt]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "mode", "native", "hidden", "topP", "temperature", "color", "permission", "model", "variant", "prompt", "options", "steps"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['subagent', 'primary', 'all']):
            raise ValueError("must be one of enum values ('subagent', 'primary', 'all')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Agent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in permission (list)
        _items = []
        if self.permission:
            for _item_permission in self.permission:
                if _item_permission:
                    _items.append(_item_permission.to_dict())
            _dict['permission'] = _items
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Agent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "mode": obj.get("mode"),
            "native": obj.get("native"),
            "hidden": obj.get("hidden"),
            "topP": obj.get("topP"),
            "temperature": obj.get("temperature"),
            "color": obj.get("color"),
            "permission": [PermissionRule.from_dict(_item) for _item in obj["permission"]] if obj.get("permission") is not None else None,
            "model": SessionPromptAsyncRequestModel.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "variant": obj.get("variant"),
            "prompt": obj.get("prompt"),
            "options": obj.get("options"),
            "steps": obj.get("steps")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


