# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from opencode_sdk.models.part import Part
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GlobalEventPayloadAnyOf9Properties(BaseModel):
    """
    GlobalEventPayloadAnyOf9Properties
    """ # noqa: E501
    session_id: Annotated[str, Field(strict=True)] = Field(alias="sessionID")
    part: Part
    time: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["sessionID", "part", "time"]

    @field_validator('session_id', mode="before")
    def session_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^ses", value):
            raise ValueError(r"must validate the regular expression /^ses/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GlobalEventPayloadAnyOf9Properties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of part
        if self.part:
            _dict['part'] = self.part.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GlobalEventPayloadAnyOf9Properties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionID": obj.get("sessionID"),
            "part": Part.from_dict(obj["part"]) if obj.get("part") is not None else None,
            "time": obj.get("time")
        })
        return _obj


