# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opencode_sdk.models.global_event_payload_any_of64_properties_tool import GlobalEventPayloadAnyOf64PropertiesTool
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GlobalEventPayloadAnyOf64Properties(BaseModel):
    """
    GlobalEventPayloadAnyOf64Properties
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)]
    session_id: Annotated[str, Field(strict=True)] = Field(alias="sessionID")
    permission: StrictStr
    patterns: List[StrictStr]
    metadata: Dict[str, Any]
    always: List[StrictStr]
    tool: Optional[GlobalEventPayloadAnyOf64PropertiesTool] = None
    __properties: ClassVar[List[str]] = ["id", "sessionID", "permission", "patterns", "metadata", "always", "tool"]

    @field_validator('id', mode="before")
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^per", value):
            raise ValueError(r"must validate the regular expression /^per/")
        return value

    @field_validator('session_id', mode="before")
    def session_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^ses", value):
            raise ValueError(r"must validate the regular expression /^ses/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GlobalEventPayloadAnyOf64Properties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tool
        if self.tool:
            _dict['tool'] = self.tool.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GlobalEventPayloadAnyOf64Properties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sessionID": obj.get("sessionID"),
            "permission": obj.get("permission"),
            "patterns": obj.get("patterns"),
            "metadata": obj.get("metadata"),
            "always": obj.get("always"),
            "tool": GlobalEventPayloadAnyOf64PropertiesTool.from_dict(obj["tool"]) if obj.get("tool") is not None else None
        })
        return _obj


