# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from opencode_sdk.models.integration_attempt_status_any_of import IntegrationAttemptStatusAnyOf
from opencode_sdk.models.integration_attempt_status_any_of1 import IntegrationAttemptStatusAnyOf1
from opencode_sdk.models.integration_attempt_status_any_of2 import IntegrationAttemptStatusAnyOf2
from opencode_sdk.models.integration_attempt_status_any_of3 import IntegrationAttemptStatusAnyOf3
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

INTEGRATIONATTEMPTSTATUS_ANY_OF_SCHEMAS = ["IntegrationAttemptStatusAnyOf", "IntegrationAttemptStatusAnyOf1", "IntegrationAttemptStatusAnyOf2", "IntegrationAttemptStatusAnyOf3"]

class IntegrationAttemptStatus(BaseModel):
    """
    IntegrationAttemptStatus
    """

    # data type: IntegrationAttemptStatusAnyOf
    anyof_schema_1_validator: Optional[IntegrationAttemptStatusAnyOf] = None
    # data type: IntegrationAttemptStatusAnyOf1
    anyof_schema_2_validator: Optional[IntegrationAttemptStatusAnyOf1] = None
    # data type: IntegrationAttemptStatusAnyOf2
    anyof_schema_3_validator: Optional[IntegrationAttemptStatusAnyOf2] = None
    # data type: IntegrationAttemptStatusAnyOf3
    anyof_schema_4_validator: Optional[IntegrationAttemptStatusAnyOf3] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[IntegrationAttemptStatusAnyOf, IntegrationAttemptStatusAnyOf1, IntegrationAttemptStatusAnyOf2, IntegrationAttemptStatusAnyOf3]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "IntegrationAttemptStatusAnyOf", "IntegrationAttemptStatusAnyOf1", "IntegrationAttemptStatusAnyOf2", "IntegrationAttemptStatusAnyOf3" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = IntegrationAttemptStatus.model_construct()
        error_messages = []
        # validate data type: IntegrationAttemptStatusAnyOf
        if not isinstance(v, IntegrationAttemptStatusAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegrationAttemptStatusAnyOf`")
        else:
            return v

        # validate data type: IntegrationAttemptStatusAnyOf1
        if not isinstance(v, IntegrationAttemptStatusAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegrationAttemptStatusAnyOf1`")
        else:
            return v

        # validate data type: IntegrationAttemptStatusAnyOf2
        if not isinstance(v, IntegrationAttemptStatusAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegrationAttemptStatusAnyOf2`")
        else:
            return v

        # validate data type: IntegrationAttemptStatusAnyOf3
        if not isinstance(v, IntegrationAttemptStatusAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegrationAttemptStatusAnyOf3`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in IntegrationAttemptStatus with anyOf schemas: IntegrationAttemptStatusAnyOf, IntegrationAttemptStatusAnyOf1, IntegrationAttemptStatusAnyOf2, IntegrationAttemptStatusAnyOf3. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[IntegrationAttemptStatusAnyOf] = None
        try:
            instance.actual_instance = IntegrationAttemptStatusAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[IntegrationAttemptStatusAnyOf1] = None
        try:
            instance.actual_instance = IntegrationAttemptStatusAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[IntegrationAttemptStatusAnyOf2] = None
        try:
            instance.actual_instance = IntegrationAttemptStatusAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[IntegrationAttemptStatusAnyOf3] = None
        try:
            instance.actual_instance = IntegrationAttemptStatusAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into IntegrationAttemptStatus with anyOf schemas: IntegrationAttemptStatusAnyOf, IntegrationAttemptStatusAnyOf1, IntegrationAttemptStatusAnyOf2, IntegrationAttemptStatusAnyOf3. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], IntegrationAttemptStatusAnyOf, IntegrationAttemptStatusAnyOf1, IntegrationAttemptStatusAnyOf2, IntegrationAttemptStatusAnyOf3]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


