# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opencode_sdk.models.provider_config_options_header_timeout import ProviderConfigOptionsHeaderTimeout
from opencode_sdk.models.provider_config_options_timeout import ProviderConfigOptionsTimeout
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProviderConfigOptions(BaseModel):
    """
    ProviderConfigOptions
    """ # noqa: E501
    api_key: Optional[StrictStr] = Field(default=None, alias="apiKey")
    base_url: Optional[StrictStr] = Field(default=None, alias="baseURL")
    enterprise_url: Optional[StrictStr] = Field(default=None, alias="enterpriseUrl")
    set_cache_key: Optional[StrictBool] = Field(default=None, alias="setCacheKey")
    timeout: Optional[ProviderConfigOptionsTimeout] = None
    header_timeout: Optional[ProviderConfigOptionsHeaderTimeout] = Field(default=None, alias="headerTimeout")
    chunk_timeout: Optional[Annotated[int, Field(strict=True, gt=0)]] = Field(default=None, alias="chunkTimeout")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiKey", "baseURL", "enterpriseUrl", "setCacheKey", "timeout", "headerTimeout", "chunkTimeout"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderConfigOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of timeout
        if self.timeout:
            _dict['timeout'] = self.timeout.to_dict()
        # override the default output from pydantic by calling `to_dict()` of header_timeout
        if self.header_timeout:
            _dict['headerTimeout'] = self.header_timeout.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderConfigOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiKey": obj.get("apiKey"),
            "baseURL": obj.get("baseURL"),
            "enterpriseUrl": obj.get("enterpriseUrl"),
            "setCacheKey": obj.get("setCacheKey"),
            "timeout": ProviderConfigOptionsTimeout.from_dict(obj["timeout"]) if obj.get("timeout") is not None else None,
            "headerTimeout": ProviderConfigOptionsHeaderTimeout.from_dict(obj["headerTimeout"]) if obj.get("headerTimeout") is not None else None,
            "chunkTimeout": obj.get("chunkTimeout")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


