# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from opencode_sdk.models.api_error import APIError
from opencode_sdk.models.retry_part_time import RetryPartTime
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RetryPart(BaseModel):
    """
    RetryPart
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)]
    session_id: Annotated[str, Field(strict=True)] = Field(alias="sessionID")
    message_id: Annotated[str, Field(strict=True)] = Field(alias="messageID")
    type: StrictStr
    attempt: Annotated[int, Field(strict=True, ge=0)]
    error: APIError
    time: RetryPartTime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "sessionID", "messageID", "type", "attempt", "error", "time"]

    @field_validator('id', mode="before")
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^prt", value):
            raise ValueError(r"must validate the regular expression /^prt/")
        return value

    @field_validator('session_id', mode="before")
    def session_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^ses", value):
            raise ValueError(r"must validate the regular expression /^ses/")
        return value

    @field_validator('message_id', mode="before")
    def message_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^msg", value):
            raise ValueError(r"must validate the regular expression /^msg/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['retry']):
            raise ValueError("must be one of enum values ('retry')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetryPart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time
        if self.time:
            _dict['time'] = self.time.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetryPart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sessionID": obj.get("sessionID"),
            "messageID": obj.get("messageID"),
            "type": obj.get("type"),
            "attempt": obj.get("attempt"),
            "error": APIError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "time": RetryPartTime.from_dict(obj["time"]) if obj.get("time") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


