# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opencode_sdk.models.permission_rule import PermissionRule
from opencode_sdk.models.session_create_request_model import SessionCreateRequestModel
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionCreateRequest(BaseModel):
    """
    SessionCreateRequest
    """ # noqa: E501
    parent_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="parentID")
    title: Optional[StrictStr] = None
    agent: Optional[StrictStr] = None
    model: Optional[SessionCreateRequestModel] = None
    metadata: Optional[Dict[str, Any]] = None
    permission: Optional[List[PermissionRule]] = None
    workspace_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="workspaceID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["parentID", "title", "agent", "model", "metadata", "permission", "workspaceID"]

    @field_validator('parent_id', mode="before")
    def parent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^ses", value):
            raise ValueError(r"must validate the regular expression /^ses/")
        return value

    @field_validator('workspace_id', mode="before")
    def workspace_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^wrk", value):
            raise ValueError(r"must validate the regular expression /^wrk/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in permission (list)
        _items = []
        if self.permission:
            for _item_permission in self.permission:
                if _item_permission:
                    _items.append(_item_permission.to_dict())
            _dict['permission'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if workspace_id (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_id is None and "workspace_id" in self.model_fields_set:
            _dict['workspaceID'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parentID": obj.get("parentID"),
            "title": obj.get("title"),
            "agent": obj.get("agent"),
            "model": SessionCreateRequestModel.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "metadata": obj.get("metadata"),
            "permission": [PermissionRule.from_dict(_item) for _item in obj["permission"]] if obj.get("permission") is not None else None,
            "workspaceID": obj.get("workspaceID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


