# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opencode_sdk.models.global_event_payload_any_of30_properties import GlobalEventPayloadAnyOf30Properties
from opencode_sdk.models.location_ref import LocationRef
from opencode_sdk.models.session_status_durable import SessionStatusDurable
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionNextToolInputDelta(BaseModel):
    """
    SessionNextToolInputDelta
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)]
    metadata: Optional[Dict[str, Any]] = None
    type: StrictStr
    durable: Optional[SessionStatusDurable] = None
    location: Optional[LocationRef] = None
    data: GlobalEventPayloadAnyOf30Properties
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "metadata", "type", "durable", "location", "data"]

    @field_validator('id', mode="before")
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^evt_", value):
            raise ValueError(r"must validate the regular expression /^evt_/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['session.next.tool.input.delta']):
            raise ValueError("must be one of enum values ('session.next.tool.input.delta')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionNextToolInputDelta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of durable
        if self.durable:
            _dict['durable'] = self.durable.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionNextToolInputDelta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "type": obj.get("type"),
            "durable": SessionStatusDurable.from_dict(obj["durable"]) if obj.get("durable") is not None else None,
            "location": LocationRef.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "data": GlobalEventPayloadAnyOf30Properties.from_dict(obj["data"]) if obj.get("data") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


