# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from opencode_sdk.models.session_next_agent_switched import SessionNextAgentSwitched
from opencode_sdk.models.session_next_compaction_ended import SessionNextCompactionEnded
from opencode_sdk.models.session_next_compaction_started import SessionNextCompactionStarted
from opencode_sdk.models.session_next_context_updated import SessionNextContextUpdated
from opencode_sdk.models.session_next_model_switched import SessionNextModelSwitched
from opencode_sdk.models.session_next_moved import SessionNextMoved
from opencode_sdk.models.session_next_prompt_admitted import SessionNextPromptAdmitted
from opencode_sdk.models.session_next_prompted import SessionNextPrompted
from opencode_sdk.models.session_next_reasoning_ended import SessionNextReasoningEnded
from opencode_sdk.models.session_next_reasoning_started import SessionNextReasoningStarted
from opencode_sdk.models.session_next_retried import SessionNextRetried
from opencode_sdk.models.session_next_revert_cleared import SessionNextRevertCleared
from opencode_sdk.models.session_next_revert_committed import SessionNextRevertCommitted
from opencode_sdk.models.session_next_revert_staged import SessionNextRevertStaged
from opencode_sdk.models.session_next_shell_ended import SessionNextShellEnded
from opencode_sdk.models.session_next_shell_started import SessionNextShellStarted
from opencode_sdk.models.session_next_step_ended import SessionNextStepEnded
from opencode_sdk.models.session_next_step_failed import SessionNextStepFailed
from opencode_sdk.models.session_next_step_started import SessionNextStepStarted
from opencode_sdk.models.session_next_synthetic import SessionNextSynthetic
from opencode_sdk.models.session_next_text_ended import SessionNextTextEnded
from opencode_sdk.models.session_next_text_started import SessionNextTextStarted
from opencode_sdk.models.session_next_tool_called import SessionNextToolCalled
from opencode_sdk.models.session_next_tool_failed import SessionNextToolFailed
from opencode_sdk.models.session_next_tool_input_ended import SessionNextToolInputEnded
from opencode_sdk.models.session_next_tool_input_started import SessionNextToolInputStarted
from opencode_sdk.models.session_next_tool_progress import SessionNextToolProgress
from opencode_sdk.models.session_next_tool_success import SessionNextToolSuccess
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SESSIONDURABLEEVENT_ONE_OF_SCHEMAS = ["SessionNextAgentSwitched", "SessionNextCompactionEnded", "SessionNextCompactionStarted", "SessionNextContextUpdated", "SessionNextModelSwitched", "SessionNextMoved", "SessionNextPromptAdmitted", "SessionNextPrompted", "SessionNextReasoningEnded", "SessionNextReasoningStarted", "SessionNextRetried", "SessionNextRevertCleared", "SessionNextRevertCommitted", "SessionNextRevertStaged", "SessionNextShellEnded", "SessionNextShellStarted", "SessionNextStepEnded", "SessionNextStepFailed", "SessionNextStepStarted", "SessionNextSynthetic", "SessionNextTextEnded", "SessionNextTextStarted", "SessionNextToolCalled", "SessionNextToolFailed", "SessionNextToolInputEnded", "SessionNextToolInputStarted", "SessionNextToolProgress", "SessionNextToolSuccess"]

class SessionDurableEvent(BaseModel):
    """
    SessionDurableEvent
    """
    # data type: SessionNextAgentSwitched
    oneof_schema_1_validator: Optional[SessionNextAgentSwitched] = None
    # data type: SessionNextModelSwitched
    oneof_schema_2_validator: Optional[SessionNextModelSwitched] = None
    # data type: SessionNextMoved
    oneof_schema_3_validator: Optional[SessionNextMoved] = None
    # data type: SessionNextPrompted
    oneof_schema_4_validator: Optional[SessionNextPrompted] = None
    # data type: SessionNextPromptAdmitted
    oneof_schema_5_validator: Optional[SessionNextPromptAdmitted] = None
    # data type: SessionNextContextUpdated
    oneof_schema_6_validator: Optional[SessionNextContextUpdated] = None
    # data type: SessionNextSynthetic
    oneof_schema_7_validator: Optional[SessionNextSynthetic] = None
    # data type: SessionNextShellStarted
    oneof_schema_8_validator: Optional[SessionNextShellStarted] = None
    # data type: SessionNextShellEnded
    oneof_schema_9_validator: Optional[SessionNextShellEnded] = None
    # data type: SessionNextStepStarted
    oneof_schema_10_validator: Optional[SessionNextStepStarted] = None
    # data type: SessionNextStepEnded
    oneof_schema_11_validator: Optional[SessionNextStepEnded] = None
    # data type: SessionNextStepFailed
    oneof_schema_12_validator: Optional[SessionNextStepFailed] = None
    # data type: SessionNextTextStarted
    oneof_schema_13_validator: Optional[SessionNextTextStarted] = None
    # data type: SessionNextTextEnded
    oneof_schema_14_validator: Optional[SessionNextTextEnded] = None
    # data type: SessionNextToolInputStarted
    oneof_schema_15_validator: Optional[SessionNextToolInputStarted] = None
    # data type: SessionNextToolInputEnded
    oneof_schema_16_validator: Optional[SessionNextToolInputEnded] = None
    # data type: SessionNextToolCalled
    oneof_schema_17_validator: Optional[SessionNextToolCalled] = None
    # data type: SessionNextToolProgress
    oneof_schema_18_validator: Optional[SessionNextToolProgress] = None
    # data type: SessionNextToolSuccess
    oneof_schema_19_validator: Optional[SessionNextToolSuccess] = None
    # data type: SessionNextToolFailed
    oneof_schema_20_validator: Optional[SessionNextToolFailed] = None
    # data type: SessionNextReasoningStarted
    oneof_schema_21_validator: Optional[SessionNextReasoningStarted] = None
    # data type: SessionNextReasoningEnded
    oneof_schema_22_validator: Optional[SessionNextReasoningEnded] = None
    # data type: SessionNextRetried
    oneof_schema_23_validator: Optional[SessionNextRetried] = None
    # data type: SessionNextCompactionStarted
    oneof_schema_24_validator: Optional[SessionNextCompactionStarted] = None
    # data type: SessionNextCompactionEnded
    oneof_schema_25_validator: Optional[SessionNextCompactionEnded] = None
    # data type: SessionNextRevertStaged
    oneof_schema_26_validator: Optional[SessionNextRevertStaged] = None
    # data type: SessionNextRevertCleared
    oneof_schema_27_validator: Optional[SessionNextRevertCleared] = None
    # data type: SessionNextRevertCommitted
    oneof_schema_28_validator: Optional[SessionNextRevertCommitted] = None
    actual_instance: Optional[Union[SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess]] = None
    one_of_schemas: Set[str] = { "SessionNextAgentSwitched", "SessionNextCompactionEnded", "SessionNextCompactionStarted", "SessionNextContextUpdated", "SessionNextModelSwitched", "SessionNextMoved", "SessionNextPromptAdmitted", "SessionNextPrompted", "SessionNextReasoningEnded", "SessionNextReasoningStarted", "SessionNextRetried", "SessionNextRevertCleared", "SessionNextRevertCommitted", "SessionNextRevertStaged", "SessionNextShellEnded", "SessionNextShellStarted", "SessionNextStepEnded", "SessionNextStepFailed", "SessionNextStepStarted", "SessionNextSynthetic", "SessionNextTextEnded", "SessionNextTextStarted", "SessionNextToolCalled", "SessionNextToolFailed", "SessionNextToolInputEnded", "SessionNextToolInputStarted", "SessionNextToolProgress", "SessionNextToolSuccess" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SessionDurableEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: SessionNextAgentSwitched
        if not isinstance(v, SessionNextAgentSwitched):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextAgentSwitched`")
        else:
            match += 1
        # validate data type: SessionNextModelSwitched
        if not isinstance(v, SessionNextModelSwitched):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextModelSwitched`")
        else:
            match += 1
        # validate data type: SessionNextMoved
        if not isinstance(v, SessionNextMoved):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextMoved`")
        else:
            match += 1
        # validate data type: SessionNextPrompted
        if not isinstance(v, SessionNextPrompted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextPrompted`")
        else:
            match += 1
        # validate data type: SessionNextPromptAdmitted
        if not isinstance(v, SessionNextPromptAdmitted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextPromptAdmitted`")
        else:
            match += 1
        # validate data type: SessionNextContextUpdated
        if not isinstance(v, SessionNextContextUpdated):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextContextUpdated`")
        else:
            match += 1
        # validate data type: SessionNextSynthetic
        if not isinstance(v, SessionNextSynthetic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextSynthetic`")
        else:
            match += 1
        # validate data type: SessionNextShellStarted
        if not isinstance(v, SessionNextShellStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextShellStarted`")
        else:
            match += 1
        # validate data type: SessionNextShellEnded
        if not isinstance(v, SessionNextShellEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextShellEnded`")
        else:
            match += 1
        # validate data type: SessionNextStepStarted
        if not isinstance(v, SessionNextStepStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextStepStarted`")
        else:
            match += 1
        # validate data type: SessionNextStepEnded
        if not isinstance(v, SessionNextStepEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextStepEnded`")
        else:
            match += 1
        # validate data type: SessionNextStepFailed
        if not isinstance(v, SessionNextStepFailed):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextStepFailed`")
        else:
            match += 1
        # validate data type: SessionNextTextStarted
        if not isinstance(v, SessionNextTextStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextTextStarted`")
        else:
            match += 1
        # validate data type: SessionNextTextEnded
        if not isinstance(v, SessionNextTextEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextTextEnded`")
        else:
            match += 1
        # validate data type: SessionNextToolInputStarted
        if not isinstance(v, SessionNextToolInputStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolInputStarted`")
        else:
            match += 1
        # validate data type: SessionNextToolInputEnded
        if not isinstance(v, SessionNextToolInputEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolInputEnded`")
        else:
            match += 1
        # validate data type: SessionNextToolCalled
        if not isinstance(v, SessionNextToolCalled):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolCalled`")
        else:
            match += 1
        # validate data type: SessionNextToolProgress
        if not isinstance(v, SessionNextToolProgress):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolProgress`")
        else:
            match += 1
        # validate data type: SessionNextToolSuccess
        if not isinstance(v, SessionNextToolSuccess):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolSuccess`")
        else:
            match += 1
        # validate data type: SessionNextToolFailed
        if not isinstance(v, SessionNextToolFailed):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextToolFailed`")
        else:
            match += 1
        # validate data type: SessionNextReasoningStarted
        if not isinstance(v, SessionNextReasoningStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextReasoningStarted`")
        else:
            match += 1
        # validate data type: SessionNextReasoningEnded
        if not isinstance(v, SessionNextReasoningEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextReasoningEnded`")
        else:
            match += 1
        # validate data type: SessionNextRetried
        if not isinstance(v, SessionNextRetried):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextRetried`")
        else:
            match += 1
        # validate data type: SessionNextCompactionStarted
        if not isinstance(v, SessionNextCompactionStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextCompactionStarted`")
        else:
            match += 1
        # validate data type: SessionNextCompactionEnded
        if not isinstance(v, SessionNextCompactionEnded):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextCompactionEnded`")
        else:
            match += 1
        # validate data type: SessionNextRevertStaged
        if not isinstance(v, SessionNextRevertStaged):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextRevertStaged`")
        else:
            match += 1
        # validate data type: SessionNextRevertCleared
        if not isinstance(v, SessionNextRevertCleared):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextRevertCleared`")
        else:
            match += 1
        # validate data type: SessionNextRevertCommitted
        if not isinstance(v, SessionNextRevertCommitted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SessionNextRevertCommitted`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SessionDurableEvent with oneOf schemas: SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SessionDurableEvent with oneOf schemas: SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SessionNextAgentSwitched
        try:
            instance.actual_instance = SessionNextAgentSwitched.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextModelSwitched
        try:
            instance.actual_instance = SessionNextModelSwitched.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextMoved
        try:
            instance.actual_instance = SessionNextMoved.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextPrompted
        try:
            instance.actual_instance = SessionNextPrompted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextPromptAdmitted
        try:
            instance.actual_instance = SessionNextPromptAdmitted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextContextUpdated
        try:
            instance.actual_instance = SessionNextContextUpdated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextSynthetic
        try:
            instance.actual_instance = SessionNextSynthetic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextShellStarted
        try:
            instance.actual_instance = SessionNextShellStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextShellEnded
        try:
            instance.actual_instance = SessionNextShellEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextStepStarted
        try:
            instance.actual_instance = SessionNextStepStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextStepEnded
        try:
            instance.actual_instance = SessionNextStepEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextStepFailed
        try:
            instance.actual_instance = SessionNextStepFailed.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextTextStarted
        try:
            instance.actual_instance = SessionNextTextStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextTextEnded
        try:
            instance.actual_instance = SessionNextTextEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolInputStarted
        try:
            instance.actual_instance = SessionNextToolInputStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolInputEnded
        try:
            instance.actual_instance = SessionNextToolInputEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolCalled
        try:
            instance.actual_instance = SessionNextToolCalled.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolProgress
        try:
            instance.actual_instance = SessionNextToolProgress.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolSuccess
        try:
            instance.actual_instance = SessionNextToolSuccess.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextToolFailed
        try:
            instance.actual_instance = SessionNextToolFailed.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextReasoningStarted
        try:
            instance.actual_instance = SessionNextReasoningStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextReasoningEnded
        try:
            instance.actual_instance = SessionNextReasoningEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextRetried
        try:
            instance.actual_instance = SessionNextRetried.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextCompactionStarted
        try:
            instance.actual_instance = SessionNextCompactionStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextCompactionEnded
        try:
            instance.actual_instance = SessionNextCompactionEnded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextRevertStaged
        try:
            instance.actual_instance = SessionNextRevertStaged.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextRevertCleared
        try:
            instance.actual_instance = SessionNextRevertCleared.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SessionNextRevertCommitted
        try:
            instance.actual_instance = SessionNextRevertCommitted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SessionDurableEvent with oneOf schemas: SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SessionDurableEvent with oneOf schemas: SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], SessionNextAgentSwitched, SessionNextCompactionEnded, SessionNextCompactionStarted, SessionNextContextUpdated, SessionNextModelSwitched, SessionNextMoved, SessionNextPromptAdmitted, SessionNextPrompted, SessionNextReasoningEnded, SessionNextReasoningStarted, SessionNextRetried, SessionNextRevertCleared, SessionNextRevertCommitted, SessionNextRevertStaged, SessionNextShellEnded, SessionNextShellStarted, SessionNextStepEnded, SessionNextStepFailed, SessionNextStepStarted, SessionNextSynthetic, SessionNextTextEnded, SessionNextTextStarted, SessionNextToolCalled, SessionNextToolFailed, SessionNextToolInputEnded, SessionNextToolInputStarted, SessionNextToolProgress, SessionNextToolSuccess]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


