# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from opencode_sdk.models.agent_part_input import AgentPartInput
from opencode_sdk.models.file_part_input import FilePartInput
from opencode_sdk.models.subtask_part_input import SubtaskPartInput
from opencode_sdk.models.text_part_input import TextPartInput
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

SESSIONPROMPTREQUESTPARTSINNER_ANY_OF_SCHEMAS = ["AgentPartInput", "FilePartInput", "SubtaskPartInput", "TextPartInput"]

class SessionPromptRequestPartsInner(BaseModel):
    """
    SessionPromptRequestPartsInner
    """

    # data type: TextPartInput
    anyof_schema_1_validator: Optional[TextPartInput] = None
    # data type: FilePartInput
    anyof_schema_2_validator: Optional[FilePartInput] = None
    # data type: AgentPartInput
    anyof_schema_3_validator: Optional[AgentPartInput] = None
    # data type: SubtaskPartInput
    anyof_schema_4_validator: Optional[SubtaskPartInput] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[AgentPartInput, FilePartInput, SubtaskPartInput, TextPartInput]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "AgentPartInput", "FilePartInput", "SubtaskPartInput", "TextPartInput" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = SessionPromptRequestPartsInner.model_construct()
        error_messages = []
        # validate data type: TextPartInput
        if not isinstance(v, TextPartInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextPartInput`")
        else:
            return v

        # validate data type: FilePartInput
        if not isinstance(v, FilePartInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilePartInput`")
        else:
            return v

        # validate data type: AgentPartInput
        if not isinstance(v, AgentPartInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AgentPartInput`")
        else:
            return v

        # validate data type: SubtaskPartInput
        if not isinstance(v, SubtaskPartInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SubtaskPartInput`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in SessionPromptRequestPartsInner with anyOf schemas: AgentPartInput, FilePartInput, SubtaskPartInput, TextPartInput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[TextPartInput] = None
        try:
            instance.actual_instance = TextPartInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[FilePartInput] = None
        try:
            instance.actual_instance = FilePartInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[AgentPartInput] = None
        try:
            instance.actual_instance = AgentPartInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[SubtaskPartInput] = None
        try:
            instance.actual_instance = SubtaskPartInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SessionPromptRequestPartsInner with anyOf schemas: AgentPartInput, FilePartInput, SubtaskPartInput, TextPartInput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AgentPartInput, FilePartInput, SubtaskPartInput, TextPartInput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


