# coding: utf-8

"""
    opencode

    opencode api

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from opencode_sdk.models.skill_v2_directory_source import SkillV2DirectorySource
from opencode_sdk.models.skill_v2_embedded_source import SkillV2EmbeddedSource
from opencode_sdk.models.skill_v2_url_source import SkillV2UrlSource
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

SKILLV2SOURCE_ANY_OF_SCHEMAS = ["SkillV2DirectorySource", "SkillV2EmbeddedSource", "SkillV2UrlSource"]

class SkillV2Source(BaseModel):
    """
    SkillV2Source
    """

    # data type: SkillV2DirectorySource
    anyof_schema_1_validator: Optional[SkillV2DirectorySource] = None
    # data type: SkillV2UrlSource
    anyof_schema_2_validator: Optional[SkillV2UrlSource] = None
    # data type: SkillV2EmbeddedSource
    anyof_schema_3_validator: Optional[SkillV2EmbeddedSource] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[SkillV2DirectorySource, SkillV2EmbeddedSource, SkillV2UrlSource]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "SkillV2DirectorySource", "SkillV2EmbeddedSource", "SkillV2UrlSource" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = SkillV2Source.model_construct()
        error_messages = []
        # validate data type: SkillV2DirectorySource
        if not isinstance(v, SkillV2DirectorySource):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SkillV2DirectorySource`")
        else:
            return v

        # validate data type: SkillV2UrlSource
        if not isinstance(v, SkillV2UrlSource):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SkillV2UrlSource`")
        else:
            return v

        # validate data type: SkillV2EmbeddedSource
        if not isinstance(v, SkillV2EmbeddedSource):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SkillV2EmbeddedSource`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in SkillV2Source with anyOf schemas: SkillV2DirectorySource, SkillV2EmbeddedSource, SkillV2UrlSource. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[SkillV2DirectorySource] = None
        try:
            instance.actual_instance = SkillV2DirectorySource.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[SkillV2UrlSource] = None
        try:
            instance.actual_instance = SkillV2UrlSource.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[SkillV2EmbeddedSource] = None
        try:
            instance.actual_instance = SkillV2EmbeddedSource.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SkillV2Source with anyOf schemas: SkillV2DirectorySource, SkillV2EmbeddedSource, SkillV2UrlSource. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], SkillV2DirectorySource, SkillV2EmbeddedSource, SkillV2UrlSource]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


